stats/slabinfo: fix /lkp/lkp/src/stats/slabinfo:17:in `block in <main>': undefined method `size' for nil:NilClass
2017-09-29 16:28:19.164475500 [lkp process-result-queue 58732] /lkp/lkp/src/stats/slabinfo:17:in `block in <main>': undefined method `size' for nil:NilClass (NoMethodError)
2017-09-29 16:28:19.189552500 [lkp process-result-queue 58732] from /lkp/lkp/src/stats/slabinfo:4:in `each_line'
2017-09-29 16:28:19.193001500 [lkp process-result-queue 58732] from /lkp/lkp/src/stats/slabinfo:4:in `<main>'
2017-09-29 16:28:19.204124500 ERROR [lkp process-result-queue 58732] /lkp/lkp/src/stats/slabinfo /result/chromeswap/1-uniform-50-0.5-performance/lkp-hsw-d01/debian-x86_64-2016-08-31.cgz/x86_64-rhel-7.2/gcc-6/004c79d19d0e43fc78d464adc28e7ccf26635c57/1/slabinfo < /result/chromeswap/1-uniform-50-0.5-performance/lkp-hsw-d01/debian-x86_64-2016-08-31.cgz/x86_64-rhel-7.2/gcc-6/004c79d19d0e43fc78d464adc28e7ccf26635c57/1/slabinfo exit code 1, check /dev/shm/lkp-stats.T5IEJXMg

the root cause is unknown, some times, 0Day will get a binary file of slabinfo while what we expect is a text file

Signed-off-by: Li Zhijian <zhijianx.li@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>