lib/git.sh: indicate git branch with --branch
not all git repos have origin/master branch

for local user,
if local user run "lkp install xxx" for several times.
from the second time, /tmp/xxx.git is existed
when this git tree does not have origin/master branch, install will fail.

the error like:
Making nvml benchmark for ubuntu
timeout 60m git remote update origin
Fetching origin
timeout 60m git checkout -q origin/master
error: pathspec 'origin/master' did not match any file(s) known to git.
timeout 60m git remote update origin
Fetching origin
timeout 60m git checkout -q origin/master
error: pathspec 'origin/master' did not match any file(s) known to git.
Making nvml-LKP failed

Signed-off-by: Li Zhijian <zhijianx.li@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>