stats/build-pkg: add backslash
\1 need to add backslash after single quotes are replaced with double quotes

example:

  input: "write.c:186:23: error: ‘io_block_t’ undeclared (first use in this function); did you mean ‘__clock_t’?"

  when "\1"
  output: write.c:error‘io_block_tundeclaredfirst-use-in-this-function)did-you-mean__clock_t’?: 1

  when '\1', "\\1"
  output: write.c:error:‘io_block_t’undeclared(first-use-in-this-function);did-you-mean‘__clock_t’?: 1

Signed-off-by: Lin Jiaxin <linjiaxin5@huawei.com>