pack/piglit-addon/groups: move utf-8 failed cases to broken temporarily
The reason of the broken case is as below:
Traceback (most recent call last):
  File "/lkp/benchmarks/piglit/lib/piglit/framework/test/base.py", line 209, in execute
    self.run()
  File "/lkp/benchmarks/piglit/lib/piglit/framework/test/base.py", line 270, in run
    self._run_command()
  File "/lkp/benchmarks/piglit/lib/piglit/framework/test/base.py", line 337, in _run_command
    out, err = proc.communicate(timeout=self.timeout)
  File "/usr/lib/python3.5/subprocess.py", line 802, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1486, in _communicate
    self.stdout.encoding)
  File "/usr/lib/python3.5/subprocess.py", line 706, in _translate_newlines
    data = data.decode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 106: ordinal not in range(128)

I tried to change the decode way to utf-8 but failed.
Now i am waiting for response from the community about this issue.
During the waiting, put them in the broken cases.

Signed-off-by: Xiang Dai <xiangx.dai@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>