stats/kernel-selftests: remove resctrl.pass stat
stats/kernel-selftests:455:in `<main>': undefined method `any?' for #<LKP::Stats:0x000055e619f6e9d8> (NoMethodError)

The actual pass check need depend on other pattern in input
like "ok" to judge.

Signed-off-by: Philip Li <philip.li@intel.com>