repo/linux/mips*: update mailing list to linux-mips@vger.kernel.org
Re: [mips-linux:mips-next 98/101] arch/mips/include/asm/div64.h:74:3: error: inconsistent operand constraints in an 'asm'
-----------
 Ying: I take it you'll know what to do to get the bot updated.  As it
happens it uses the old <linux-mips@linux-mips.org> MIPS/Linux mailing
list address, which has been long deprecated and then stopped working
altogether mid Jan this year.  I have updated the cc appropriately with
this reply, but would you please amend whatever the bot requires for
further notices to be sent to <linux-mips@vger.kernel.org> instead?

  Maciej
-----------

Signed-off-by: Chen Rong <rong.a.chen@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>