job: fix exception in lkp_src
/lkp/wfg/src/lib/job.rb:236:in `lkp_src': undefined method `[]' for false:FalseClass (NoMethodError)

The root cause is @job is false, loaded from a template which evaluates
to empty YAML.

Signed-off-by: Fengguang Wu <fengguang.wu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>