sbin/dump-stat: check line terminator of stat's value
To fix the following error log:
2016-07-06 10:03:07.582489500 [lkp process-result-queue 119095] /lkp/lkp/src/sbin/dump-stat:36:in `<main>': undefined method `strip!' for nil:NilClass (NoMethodError)

> This is interesting:
>
> wfg /c/linux% irb
> irb(main):001:0> ''.chomp!
> => nil
> irb(main):002:0> ''.chomp
> => ""

Right. If there is no line terminator, String.chomp! will return nil,
otherwise, it returns the chomped string w/o "\n".

There are some rare cases that result logs are not stored correctly,
which will cause some stat lines have no line terminator, and result in
the "undefined method 'strip!'" error.

Signed-off-by: Wenzhong Sun <wenzhong.sun@intel.com>
Signed-off-by: Fengguang Wu <fengguang.wu@intel.com>

i

Signed-off-by: Fengguang Wu <fengguang.wu@intel.com>