pack/libhugetlbfs-test: centos: fix compiler errors
[root@centos-lkp libhugetlbfs-test]# lkp run ./libhugetlbfs-test-2MB-64.yaml
2018-01-09 01:33:02 make
	 CC32 obj32/fallocate_basic.o
	 LD32 (lib test) obj32/fallocate_basic
	 CC32 obj32/fallocate_align.o
fallocate_align.c: In function ‘main’:
fallocate_align.c:76:22: error: ‘FALLOC_FL_PUNCH_HOLE’ undeclared (first use in this function)
  err = fallocate(fd, FALLOC_FL_PUNCH_HOLE | FALLOC_FL_KEEP_SIZE,
                      ^
fallocate_align.c:76:22: note: each undeclared identifier is reported only once for each function it appears in
fallocate_align.c:76:45: error: ‘FALLOC_FL_KEEP_SIZE’ undeclared (first use in this function)
  err = fallocate(fd, FALLOC_FL_PUNCH_HOLE | FALLOC_FL_KEEP_SIZE,
                                             ^
make[1]: *** [obj32/fallocate_align.o] Error 1
make: *** [tests/all] Error 2
make failed
  /home/lizhijian/lkp-tests/lib/debug.sh:7: die
  /home/lizhijian/lkp-tests/tests/libhugetlbfs-test:9: main
  :0:
kill 9465 vmstat --timestamp -n 10
kill 9463 dmesg --follow --decode

FALLOC_FL_PUNCH_HOLE and FALLOC_FL_KEEP_SIZE are defined at /usr/include/bits/fcntl-linux.h under debian/ubuntu
which is provided by libc, but some other distros, like centos, those 2 macro aren't defined. so it throws above
errors.

we can find similar issues:
https://github.com/lizardfs/lizardfs/issues/497

Signed-off-by: Li Zhijian <zhijianx.li@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>