pack/makepkg: add pack/makepkg to install fakeroot
makepkg needs fakeroot, we install bundle os-testsuite-0day to add fakeroot,
but clearlinux doesn't have libfakeroot.so.
------
lat_cmd.c: In function ‘main’:
lat_cmd.c:40:23: warning: implicit declaration of function ‘lmbench_usage’
[-Wimplicit-function-declaration]
    if (parallel <= 0) lmbench_usage(ac, av, usage);
                       ^~~~~~~~~~~~~
fakeroot: preload library `libfakeroot.so' not found, aborting.
------

i have tried to download libfakeroot.so from clearlinux.org,
https://download.clearlinux.org/debuginfo/lib/usr/lib64/libfakeroot.so.debug.tar.

but this libfakeroot.so.debug.tar doesn't work, it always got below error
------
root@ivb44 /usr/lib64# fakeroot
/usr/sbin/fakeroot: line 178: 21282 Segmentation fault      (core dumped)
FAKEROOTKEY=$FAKEROOTKEY LD_LIBRARY_PATH="$PATHS" LD_PRELOAD="$LIB"
${SHELL:-/bin/sh}
------

add pack/makepkg to install fakeroot, enable makepkg on clearlinux.

Signed-off-by: Liu Yiding <liuyd.fnst@cn.fujitsu.com>

Signed-off-by: Philip Li <philip.li@intel.com>