repo/spdk/spdk: change from HTTP to SSH work
Avoid following issue
------
kbuild@lkp-server01:/gitmirror/spdk$ git -c 'advice.objectNameWarning=false' fetch

error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
------

Error happended when clone by HTTP protocol (curl command).

Based on community suggestion, change from HTTP to SSH works.
https://stackoverflow.com/questions/38618885/error-rpc-failed-curl-transfer-closed-with-outstanding-read-data-remaining

Signed-off-by: Liu Yiding <yidingx.liu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>