spec: remove job_spec.rb
current code repo have removed "project" function in job.rb, so just remove it.

renyl@inn:~/lkp-tests$ rake spec
PWD = /home/renyl/lkp-tests
ENV['LKP_SRC'] = /lkp/renyl/src
/usr/bin/ruby2.2 /usr/bin/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
..............FFF..............

Failures:

  1) Job project should recognize dpdk project
     Failure/Error: expect(job.project).to eq 'dpdk'
     NoMethodError:
       undefined method `project' for #<Job:0x000000029133c0>
     # ./spec/job_spec.rb:10:in `block (3 levels) in <top (required)>'

  2) Job project should recognize qemu project
     Failure/Error: expect(job.project).to eq 'qemu'
     NoMethodError:
       undefined method `project' for #<Job:0x00000002d08d68>
     # ./spec/job_spec.rb:20:in `block (3 levels) in <top (required)>'

  3) Job project should recognize linux project
     Failure/Error: expect(job.project).to eq 'linux'
     NoMethodError:
       undefined method `project' for #<Job:0x000000028f29b8>
     # ./spec/job_spec.rb:30:in `block (3 levels) in <top (required)>'

Finished in 0.15735 seconds (files took 0.57043 seconds to load)
31 examples, 3 failures

Failed examples:

rspec ./spec/job_spec.rb:6 # Job project should recognize dpdk project
rspec ./spec/job_spec.rb:16 # Job project should recognize qemu project
rspec ./spec/job_spec.rb:26 # Job project should recognize linux project

/usr/bin/ruby2.2 /usr/bin/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
renyl@inn:~/lkp-tests$

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>