pkg/packetdrill/PKGBUILD: Clear default CPPFLAGS
etc/makepkg.conf in lkp-tests sets default CPPFLAGS(i.e.
CPPFLAGS="-D_FORTIFY_SOURCE=2") so that compiling packetdrill
gets the following error on fedora, centos and aliyun:
------------------------------------------------
/usr/include/features.h:330:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
cc1: all warnings being treated as errors
------------------------------------------------

After investigation, it's caused by the three conditions from packetdrill:
1) packetdrill use -Werror option(treat warning as error) to compile.
2) packetdrill doesn't use -O option(optimization) to compile the code
   including <features.h>.
3) <features.h> from glibc has the check that reports warning if
   _FORTIFY_SOURCE is set but optimization is not set.

debian and ubuntu have changed /usr/include/features.h to
avoid the warning, as below:
-------------------------------------------------
root@ubuntu18:~# grep -r "defined _FORTIFY_SOURCE" -A 10 /usr/include/features.h
#if defined _FORTIFY_SOURCE && _FORTIFY_SOURCE > 0 \
    && __GNUC_PREREQ (4, 1) && defined __OPTIMIZE__ && __OPTIMIZE__ > 0
# if _FORTIFY_SOURCE > 1
#  define __USE_FORTIFY_LEVEL 2
# else
#  define __USE_FORTIFY_LEVEL 1
# endif
#else
# define __USE_FORTIFY_LEVEL 0
#endif
--------------------------------------------------

fedora, centos and aliyun have not changed /usr/include/features.h
to avoid the warning, as below:
--------------------------------------------------
[root@fedora packetdrill]# grep -r "defined _FORTIFY_SOURCE" -A 10 /usr/include/features.h
#if defined _FORTIFY_SOURCE && _FORTIFY_SOURCE > 0
# if !defined __OPTIMIZE__ || __OPTIMIZE__ <= 0
#  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
# elif !__GNUC_PREREQ (4, 1)
#  warning _FORTIFY_SOURCE requires GCC 4.1 or later
# elif _FORTIFY_SOURCE > 1
#  define __USE_FORTIFY_LEVEL 2
# else
#  define __USE_FORTIFY_LEVEL 1
# endif
#endif
---------------------------------------------------

On upstream glibc code, the warning is introduced to <features.h> by:
http://sourceware.org/git/?p=glibc.git;a=commit;f=include/features.h;h=05c2c9618f583ea4acd69b3fe5ae2a2922dd2ddc

Clear default CPPFLAGS to fix the issue.

Signed-off-by: Xiao Yang <xiaox.yang@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>