jobs/phoronix-test-suite*.yaml comment out viennacl-1.0.0 since too old version
there is only one version of viennacl, it didn't update since 2013.
now it keeps telling the following error, and it relates to https://github.com/phbender/liblanelet/issues/3
/usr/include/c++/9/bits/stringfwd.h:79:11: error: reference to 'basic_string' is ambiguous
 79 | typedef basic_string<char> string;

Signed-off-by: Ma XinJian <max.xinjian@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>