stats/autotest: add check for failed test
If test failed, the RESULT_ROOT/results/default/status.json is abnormal so that the below issue occurs:
/lkp/lkp/src/stats/autotest:10:in `<main>': undefined method `empty?' for nil:NilClass (NoMethodError)

Signed-off-by: Xiang Dai <xiangx.dai@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>