setup/fs: add mount_option parameter
To fix the following error info:
error: PMEM_FS_DIR=/fs/pmem0 does not point to a PMEM device

to emulate pmem, need to add "-o dax" as mount option.

http://pmem.io/2016/02/22/pm-emulation.html

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>