repo/linux/frank-w-bpi-r2-4.14: set as private
Re: [frank-w-bpi-r2-4.14:5.12-hnat 3/11] drivers/pci/probe.c:930:39: error: 'struct device' has no member named 'msi_domain'; did you mean
-----------------
On 2021-03-22 10:11, kernel test robot wrote:
> Hi Marc,
>
> FYI, the error/warning still remains.

Please, can you stop emailing be for trees I have no control over?

Yes, this patch is completely broken. But there is nothing I can
do about it as I don't own the tree this is merged on.

Thanks,

        M.

>
> tree:   https://github.com/frank-w/BPI-R2-4.14 5.12-hnat
> head:   79ba85605b096ebba4359684a0e5d719541e14fb
> commit: 985198ae531b3360e32967e50a2f2a3fc07075ab [3/11] pci: fix MSI
> issue part 2
> config: i386-randconfig-a003-20210322 (attached as .config)
> compiler: gcc-9 (Debian 9.3.0-22) 9.3.0
-----------------

Signed-off-by: Chen Rong <rong.a.chen@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>