setup/md: Also stop acitve md before creating btrfs raid
We cannot create a new btrfs raid because of the acitve md created
by previous normal raid test.  Fix the following issue:
---------------------------------------------------------
ERROR: unable to open /dev/sdb1: Device or resource busy
ERROR: unable to open /dev/sdb2: Device or resource busy
ERROR: unable to open /dev/sdb3: Device or resource busy
---------------------------------------------------------

Signed-off-by: Xiao Yang <xiaox.yang@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>