kernel-selftests: only bind mount modules to lib for bpf
$linux_selftests_dir/lib was bind mount to /lib/modules/xxx since
bpf need ${SRC_TREE}/lib/test_bpf.ko to continue testing. but the
bind mount breaks hmm which required head file in ${SRC_TREE}/lib
to build test case.

only bind mount modules to lib for bpf test case. to fix hmm test
error:

------
tools/testing/selftests/vm/hmm-tests
1264 hmm-tests.c:34:10: fatal error: ../../../../lib/test_hmm_uapi.h: No such file or directory
1265  #include "../../../../lib/test_hmm_uapi.h"
1266           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1267 compilation terminated.
------

check that only bpf test need module located in lib:
------
linux/tools/testing/selftests$ grep -r "insmod" *
bpf/test_kmod.sh:               insmod ${SRC_TREE}/lib/test_bpf.ko 2> /dev/null
cpufreq/module.sh:# Check basic insmod/rmmod
cpufreq/module.sh:test_basic_insmod_rmmod()
cpufreq/module.sh:      insmod $1
cpufreq/module.sh:      insmod $1
cpufreq/module.sh:      test_basic_insmod_rmmod $1
cpufreq/module.sh:              insmod $2
cpufreq/module.sh:      test_basic_insmod_rmmod $1
cpufreq/module.sh:      insmod $1
cpufreq/module.sh:      insmod $1
cpufreq/module.sh:      insmod $2
gpio/gpio-mockup.sh:                    echo $msg insmod $module failed >&2
livepatch/test-callbacks.sh:#   The result is that the insmod command refuses to load the livepatch
sparc64/drivers/drivers_test.sh:                insmod ${SRC_TREE}/drivers/char/adi.ko 2> /dev/null
------

Signed-off-by: Xia Hui <hui.xia@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>