kernel_selftests: add missing dependency package
To fix the following error info:

==> /tmp/stderr <==
reuseport_bpf_numa.c:23:18: fatal error: numa.h: No such file or directory

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>