rubocop: update TargetRubyVersion to 2.3
$ rake rubocop
rubocop.patterns = []
rubocop.options = ["-D", "-c.rubocop.yml"]
Running RuboCop...
Error: Unsupported Ruby version 2.0 found in `TargetRubyVersion`
parameter (in .rubocop.yml). 2.0-compatible analysis was dropped after version 0.50.
Supported versions: 2.1, 2.2, 2.3, 2.4, 2.5
RuboCop failed!

Reported-by: Aaron Lu <aaron.lu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>