pack/xfstests: fix build error
to fix the following error info:

root@waimea /tmp/xfstests-dev# make
Building include
Building lib
Building tests
Building ltp
Building src
Building m4
Building common
    [CC]    fsstress
    [CC]    t_immutable
    [CC]    nsexec
    [CC]    cloner
    [CC]    t_getcwd
    [CC]    renameat2
    [CC]    test-nextquota
    [CC]    punch-alternating
    [CC]    e4compact
    [CC]    fiemap-tester
In file included from /usr/include/xfs/xfs.h:58:0,
                 from ../src/global.h:25,
                 from fsstress.c:20:
/usr/include/xfs/xfs_fs.h:42:8: error: redefinition of 'struct fsxattr'
 struct fsxattr {
        ^~~~~~~
In file included from fsstress.c:19:0:
/usr/include/linux/fs.h:155:8: note: originally defined here
 struct fsxattr {
        ^~~~~~~
In file included from /usr/include/xfs/xfs.h:58:0,
                 from t_immutable.c:43:
/usr/include/xfs/xfs_fs.h:42:8: error: redefinition of 'struct fsxattr'
 struct fsxattr {
        ^~~~~~~
In file included from t_immutable.c:41:0:
/usr/include/linux/fs.h:155:8: note: originally defined here
 struct fsxattr {
        ^~~~~~~
Makefile:42: recipe for target 'fsstress' failed
make[2]: *** [fsstress] Error 1
include/buildrules:30: recipe for target 'ltp' failed
make[1]: *** [ltp] Error 2
make[1]: *** Waiting for unfinished jobs....
Makefile:80: recipe for target 't_immutable' failed
make[2]: *** [t_immutable] Error 1
make[2]: *** Waiting for unfinished jobs....
include/buildrules:30: recipe for target 'src' failed
make[1]: *** [src] Error 2
Makefile:66: recipe for target 'default' failed
make: *** [default] Error 2
root@waimea /tmp/xfstests-dev#

this is a bug, can refer to below urls:

https://patchwork.kernel.org/patch/9121551/
https://patchwork.ozlabs.org/patch/616742/
http://oss.sgi.com/archives/xfs/2016-05/msg00347.html

this bug have been fixed, but need to higher version of xfsprogs,
however, can not high version from intel's repo.

root@waimea /tmp/xfstests-dev# apt-cache show xfsprogs  | grep Version
Version: 4.3.0+nmu1
Version: 3.2.1
root@waimea /tmp/xfstests-dev#

as a workround, use xfsprogs source code to build the relevant headers file,
instead of `apt-get install xfsprogs`.

detailed info can refer to: https://jira01.devtools.intel.com/browse/OLT-1403

Reviewed-by: Fengguang Wu <fengguang.wu@intel.com>
Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>