build-dpdk: add missing package
to fix the following error info:

renyl@inn:/result/build-dpdk/x86_64-native-linuxapp-gcc/afd2ff9b7e1b367172f18ba7f693dfb62bdcb2dc/gcc-5/959c1f901fc7a2ff5c48d640bfeba348e9a09e11/0$ cat make-stderr/*
make[1]: *** [app] Error 2
make[2]: *** [test] Error 2
make[2]: *** Waiting for unfinished jobs....
In file included from include/linux/resource_ext.h:19:0,
                 from include/linux/pci.h:32,
                 from build/lib/librte_eal/linuxapp/igb_uio/igb_uio.c:29:
build/lib/librte_eal/linuxapp/igb_uio/igb_uio.c: In function 'igbuio_pci_probe':
include/linux/slab.h:600:21: warning: inlining failed in call to 'kzalloc.constprop': call is unlikely and code size would grow [-Winline]
 static inline void *kzalloc(size_t size, gfp_t flags)
                     ^
build/lib/librte_eal/linuxapp/igb_uio/igb_uio.c:331:7: warning: called from here [-Winline]
  udev = kzalloc(sizeof(struct rte_uio_pci_dev), GFP_KERNEL);
       ^
make[3]: *** [resource.o] Error 1
make[3]: *** Waiting for unfinished jobs....
app/test/resource.c:36:21: fatal error: archive.h: No such file or directory
compilation terminated.
make: *** [all] Error 2
renyl@inn:/result/build-dpdk/x86_64-native-linuxapp-gcc/afd2ff9b7e1b367172f18ba7f693dfb62bdcb2dc/gcc-5/959c1f901fc7a2ff5c48d640bfeba348e9a09e11/0$

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>