pack/ltp: fix ltp pack.fail
fix the 2 issues
1. undefined reference to `minor'
------
/usr/bin/ld: ./.libs/libnuma.so: undefined reference to `minor'
/usr/bin/ld: ./.libs/libnuma.so: undefined reference to `major'
------
it needs to add sys/sysmacros.h, and this issue has been fixed in below url, update url to fix this problem.
------
https://github.com/numactl/numactl.git
------
2. required file not found
------
configure.ac:9: error: required file 'build-aux/install-sh' not found
configure.ac:9:   'automake --add-missing' can install 'install-sh'
configure.ac:13: error: required file 'build-aux/ltmain.sh' not found
configure.ac:9: error: required file 'build-aux/missing' not found
configure.ac:9:   'automake --add-missing' can install 'missing'
------
use cmd "autoreconf -f -i" to remake all files, to avoid missing file.
-f: consider all files obsolete
-i: copy missing auxiliary files

Signed-off-by: Liu Yiding <liuyd.fnst@cn.fujitsu.com>

Signed-off-by: Philip Li <philip.li@intel.com>