pkg/rt-tests: Missing dependency libnuma-dev
----
In file included from src/cyclictest/cyclictest.c:39:0:
src/cyclictest/rt_numa.h:29:18: fatal error: numa.h: No such file or
directory
 #include <numa.h>
              ^
compilation terminated.
make: *** [bld/cyclictest.o] Error 1
----

Signed-off-by: Cao jin <jinx.cao@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>