distro/depends/hwsim: hwsim/hwsim-01: ap_hs20_proxyarp run failed: No such file or directory
look into the source code, we know the test requires ip command

-----------
START ap_hs20_proxyarp 1/1
Test: Hotspot 2.0 and ProxyARP
Starting AP wlan3
[Errno 2] No such file or directory
Traceback (most recent call last):
  File "./run-tests.py", line 452, in main
    t(dev, apdev)
  File "/lkp/benchmarks/hwsim/tests/hwsim/test_ap_hs20.py", line 3827,
in test_ap_hs20_proxyarp
    stderr=open('/dev/null', 'w'))
  File "/usr/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
-----------

Signed-off-by: Li Zhijian <zhijianx.li@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>