yaml: add missing require of erb
/lkp/lkp/src/lib/yaml.rb:17:in `expand_yaml_template': undefined method `literal_double_braces' for main:Object (NoMethodError)
	from /lkp/lkp/src/lib/yaml.rb:24:in `load_yaml'
	from /lkp/lkp/src/tools/stat-test-elapsed-time:42:in `block in <main>'
	from /lkp/lkp/src/tools/stat-test-elapsed-time:42:in `map'
	from /lkp/lkp/src/tools/stat-test-elapsed-time:42:in `<main>'

Signed-off-by: Philip Li <philip.li@intel.com>