fix(distro/aliyun): use dnf instead of yum in centos7
package:
	g++ # not exist
	python3 # already exist

before:
	% yum install -y --downloadonly g++ python3
	No package g++ available.
        Package python3.aarch64 0:3.6.8-13.el7 will be installed
        % echo $?
        % 0
after:
	% yum install -y --downloadonly g++ python3
	No match for argument: g++
	Error: Unable to find a match: g++
	% echo $?
	% 1

Signed-off-by: Wang Yong <wangyong187@huawei.com>