lib/job.rb: raise when no input testbox
before fix:
  lib/job.rb:286:in `get_hosts_file': undefined method `split' for nil:NilClass (NoMethodError)
after fix:
  lib/job.rb:269:in `load_hosts_config': hosts_file doesn't exist:
  /home/weijihui/lkp-tests/hosts/, please check your testbox (RuntimeError)

Signed-off-by: Wei Jihui <weijihui2@huawei.com>