lib/tests/cassandra.sh: support openjdk 11
to fix running issue on debian 10:
ERROR: NO avaliable JAVA_HOME

but cassandra still failed on openjdk 11:
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Error: Could not find or load main class org.apache.cassandra.service.CassandraDaemon
Caused by: java.lang.ClassNotFoundException: org.apache.cassandra.service.CassandraDaemon

Signed-off-by: Xia Hui <hui.xia@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>