hwsim: update dependency package
To fix the following error info:

==> /tmp/stderr <==
/lkp/benchmarks/hwsim/tests/hwsim/../../hostapd/hostapd: error while loading shared libraries: libnl-route-3.so.200: cannot open shared object file: No such file or directory
/lkp/benchmarks/hwsim/tests/hwsim/../../hostapd/hlr_auc_gw: error while loading shared libraries: libcrypto.so.1.0.2: cannot open shared object file: No such file or directory
/lkp/benchmarks/hwsim/tests/hwsim/../../wpa_supplicant/wpa_supplicant: error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directory
/lkp/benchmarks/hwsim/tests/hwsim/../../wpa_supplicant/wpa_supplicant: error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directory
/lkp/benchmarks/hwsim/tests/hwsim/../../wpa_supplicant/wpa_supplicant: error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directory
/lkp/benchmarks/hwsim/tests/hwsim/../../wpa_supplicant/wpa_supplicant: error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directory
/lkp/benchmarks/hwsim/tests/hwsim/../../hostapd/hostapd: error while loading shared libraries: libnl-route-3.so.200: cannot open shared object file: No such file or directory

==> /tmp/stderr <==
/lkp/benchmarks/hwsim/tests/hwsim/../../wpa_supplicant/wpa_supplicant: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /lkp/benchmarks/hwsim/tests/hwsim/../../wpa_supplicant/wpa_supplicant)
  /lkp/benchmarks/hwsim/tests/hwsim/../../wpa_supplicant/wpa_supplicant: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /lkp/benchmarks/hwsim/tests/hwsim/../../wpa_supplicant/wpa_supplicant)
  Failed to connect to wpa_supplicant global interface: /tmp/wpas-wlan1  error: No such file or directory
  /lkp/benchmarks/hwsim/tests/hwsim/../../wpa_supplicant/wpa_supplicant: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /lkp/benchmarks/hwsim/tests/hwsim/../../wpa_supplicant/wpa_supplicant)
  /lkp/benchmarks/hwsim/tests/hwsim/../../wpa_supplicant/wpa_supplicant: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /lkp/benchmarks/hwsim/tests/hwsim/../../wpa_supplicant/wpa_supplicant)

==> /tmp/stderr <==
Traceback (most recent call last):
  File "./run-tests.py", line 574, in <module>
    main()
  File "./run-tests.py", line 181, in main
    mod = __import__(m.group(1))
  File "/lkp/benchmarks/hwsim/tests/hwsim/test_ap_eap.py", line 24, in <module>
    from test_ap_psk import check_mib, find_wpas_process, read_process_memory, verify_not_present, get_key_locations, set_test_assoc_ie
  File "/lkp/benchmarks/hwsim/tests/hwsim/test_ap_psk.py", line 8, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>