thrulay/PKGBUILD: download config.guess, config.sub
error: cp: cannot stat ‘/usr/share/misc/config.guess’: No such file or directory
       cp: cannot stat ‘/usr/share/misc/config.sub’: No such file or directory

reason: missing config.guess, config.sub on centos, openeuler

Signed-off-by: Lin Jiaxin <linjiaxin5@huawei.com>