distro/depends/avocado: add some testing tool to enable more tests
Fix missing cmd error.
e.g.
------
No such file or directory: 'gcc'
ERROR: [Errno 2] No such file or directory: 'make' (make raise)
ERROR: File '/usr/bin/gdbserver' not found.

Signed-off-by: Liu Yiding <yidingx.liu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>