tests/test-tools: config dns resolver
[error]
when run test-tools.yaml, error message as follows:
--2019-08-14 15:05:41--  https://pngquant.org/Ducati_side_shadow.png
Resolving pngquant.org (pngquant.org)... failed: Name or service not known.
wget: unable to resolve host address ‘pngquant.org
Error: Failed to download metadata for repo 'OS': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

vm testbox: os_mount=local openeuler aarch64 20.03, there is no "114.114.114.114 and 233.5.5.5" in /etc/resolv.conf,
it will causes dns resolution failed, so add it.

Signed-off-by: Liu Yinsi <liuyinsi@163.com>