stats/ftrace: add missing param
To fix the below issue:
2017-06-07 13:05:58.342653500 [lkp process-result-queue 18815] /lkp/lkp/src/stats/ftrace:64:in `normlize_event_data': undefined local variable or method `records' for main:Object (NameError)
2017-06-07 13:05:58.348991500 [lkp process-result-queue 18815] Did you mean? record
2017-06-07 13:05:58.368121500 [lkp process-result-queue 18815] from /lkp/lkp/src/stats/ftrace:113:in `parse_event'
2017-06-07 13:05:58.375708500 [lkp process-result-queue 18815] from /lkp/lkp/src/stats/ftrace:117:in `block in <main>'
2017-06-07 13:05:58.394228500 [lkp process-result-queue 18815] from /lkp/lkp/src/stats/ftrace:116:in `each'
2017-06-07 13:05:58.423975500 [lkp process-result-queue 18815] from /lkp/lkp/src/stats/ftrace:116:in `<main>'

Signed-off-by: Xiang Dai <xiangx.dai@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>