pkg/mdadm-selftests: Fix the failure of 05r1-re-add-nosuper
For array without metadata(e.g. mdadm -B/--build), mdadm commit 091e8e6
breaks the logic of re-add operation and trigger the following issue:
----------------------------------------------------------
++ die 'resync or recovery is happening!'
++ echo -e '\n\tERROR: resync or recovery is happening! \n'
ERROR: resync or recovery is happening!
----------------------------------------------------------

Try to fix the issue by adding a mdadm-selftests02.patch and also
rename original mdadm-selftests.patch to mdadm-selftests01.patch.

Signed-off-by: Xiao Yang <xiaox.yang@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>