kernel-selftests: Fix make kvm failed
Disable parallel make temporary since there is a bug in current parallel
make -C kvm

building kvm requires header_install target, but both of them will be
built in parallel in pratice:

 # kvm target
gcc -Wall -Wstrict-prototypes -Wuninitialized -O2 -g -std=gnu99 -fno-stack-protector -fno-PIE -I../../../../tools/include -I../../../../tools/arch/x86/include -I../../../../usr/include/ -Iinclude -Ix86_64 -Iinclude/x86_64 -I..  -pthread  -no-pie x86_64/evmcs_test.c
/usr/src/perf_selftests-x86_64-rhel-8.3-kselftests-6880fa6c56601bb8ed59df6c30fd390cc5f6dd8f/tools/testing/selftests/kvm/libkvm.a -o /usr/src/perf_selftests-x86_64-rhel-8.3-kselftests-6880fa6c56601bb8ed59df6c30fd390cc5f6dd8f/tools/testing/selftests/kvm/x86_64/evmcs_test
 # header_install target
  HDRINST usr/include/video/uvesafb.h
  HDRINST usr/include/video/sisfb.h
  HDRINST usr/include/video/edid.h
  HDRINST usr/include/drm/i915_drm.h
  HDRINST usr/include/drm/etnaviv_drm.h

../../../../usr/include/linux/kvm.h:2: error: unterminated #ifndef
 #ifndef __LINUX_KVM_H

In file included from /usr/include/x86_64-linux-gnu/sys/ioctl.h:29,
                 from include/kvm_util.h:15,
                 from demand_paging_test.c:21:
/usr/include/x86_64-linux-gnu/bits/ioctl-types.h:27:1: error: two or
more data types in declaration specifiers
 struct winsize
 ^~~~~~
In file included from demand_paging_test.c:21:
include/kvm_util.h:85:45: warning: <E2><80><98>struct
kvm_enable_cap<E2><80><99> declared inside parameter list will not be
visible outside of this definition or declaration
 int vm_enable_cap(struct kvm_vm *vm, struct kvm_enable_cap *cap);
                                             ^~~~~~~~~~~~~~

Next step, i will try to fix it in kernel side.

Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>
Signed-off-by: Philip Li <philip.li@intel.com>