pkg/swapin: missing dependency libnuma-dev
Fix:
----
usemem_migrate.c:8:20: fatal error: numaif.h: No such file or directory
 #include <numaif.h>
                   ^
compilation terminated.
make: *** [usemem_migrate] Error 1
==> ERROR: A failure occurred in build().
Aborting...
----

Signed-off-by: Cao jin <jinx.cao@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>