compare: add error handing for do_compare
As result_root may be removed manually or by cleanup service which would cause
do_compare crash, we need to add error handing to rescue in this case.

Error while comparing: /lkp/data/mresult_root/linux/storage/11/116cf51b9a9cd20f8eadace739623f9a8d358840 /lkp/data/mresult_root/linux/storage/25/258340d16adee71679792fc97668e01787002dea
/lkp/yexl/src/lib/matrix.rb:34:in `matrix_fill_missing_zeros': undefined method `size' for nil:NilClass (NoMethodError)
        from /lkp/yexl/src/lib/nresult_root.rb:155:in `matrix'
        from /lkp/yexl/src/lib/compare.rb:274:in `block in matrixes'
        from /lkp/yexl/src/lib/compare.rb:274:in `map'
        from /lkp/yexl/src/lib/compare.rb:274:in `matrixes'
        from /lkp/yexl/src/lib/compare.rb:412:in `each_changed_stat'
        from /lkp/yexl/src/lib/compare.rb:702:in `each'
        from /lkp/yexl/src/lib/compare.rb:702:in `to_a'
        from /lkp/yexl/src/lib/compare.rb:702:in `sort_stats'
        from /lkp/yexl/src/lib/compare.rb:207:in `block in do_compare'
        from /lkp/yexl/src/lib/compare.rb:205:in `map'
        from /lkp/yexl/src/lib/compare.rb:205:in `do_compare'
        from /lkp/yexl/src/lib/report.rb:226:in `do_compare'
        from /lkp/yexl/src/lib/report.rb:281:in `send_email'
        from /lkp/yexl/src/lib/report.rb:35:in `send_email'
        from /lkp/yexl/src/lkp-exec/report:299:in `<main>'

Signed-off-by: Xiaolong Ye <xiaolong.ye@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>