distro/depends/piglit-dev: update dependency
---------------------
/home/lkp/lkp-tests/tmp-pkg/piglit/src/piglit/tests/util/piglit-dispatch-init.c:47:20: fatal error: waffle.h: No such file or directory
 #include <waffle.h>
                     ^
                     compilation terminated.
---------------------
-- Build files have been written to: /tmp/build-piglit/piglit
[  0%] Built target piglit_dispatch_gen
[  0%] Building C object target_api/no_api/tests/util/CMakeFiles/piglitutil.dir/piglit-log.c.o
[  0%] Building C object target_api/no_api/tests/util/CMakeFiles/piglitutil.dir/piglit-util.c.o
[  0%] Building C object target_api/no_api/tests/util/CMakeFiles/piglitutil.dir/piglit-util-egl.c.o
[  0%] Linking C shared library ../../../../lib/libpiglitutil.so
/usr/bin/ld: cannot find -lxkbcommon
collect2: error: ld returned 1 exit status
target_api/no_api/tests/util/CMakeFiles/piglitutil.dir/build.make:148: recipe for target 'lib/libpiglitutil.so.0' failed
make[2]: *** [lib/libpiglitutil.so.0] Error 1
CMakeFiles/Makefile2:249: recipe for target 'target_api/no_api/tests/util/CMakeFiles/piglitutil.dir/all' failed
make[1]: *** [target_api/no_api/tests/util/CMakeFiles/piglitutil.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
[  0%] Built target piglit_dispatch_gen

---------------------
checking for DRM... yes
checking for PCIACCESS... yes
checking for KMOD... yes
checking for PROCPS... no
configure: error: Package requirements (libprocps) were not met:

No package 'libprocps' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables PROCPS_CFLAGS
and PROCPS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make: *** No targets specified and no makefile found.  Stop.
Fatal Error: intel-gpu-tools test lists not found.

dpkg-deb: building package 'piglit-lkp' in 'piglit-LKP.deb'.
---------------------

Signed-off-by: Li Zhijian <zhijianx.li@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>