pack/netperf: fix netlib.c:(.text+0x402f): undefined reference to `demo_interval_display'
since gcc-5, the compiling fails if c code cannot call inline functions directly by default

root@vm-lkp-nex04-8G-10 ~/netperf-netperf-2.7.0# cat hello.c
 #include <stdio.h>
 inline void foo(void) {printf("hello world 111\n");}
 void main() { foo(); printf("hello world 22222\n");}

root@vm-lkp-nex04-8G-10 ~/netperf-netperf-2.7.0# gcc hello.c
/tmp/ccnEvrCD.o: In function `main':
hello.c:(.text+0x5): undefined reference to `foo'
collect2: error: ld returned 1 exit status
root@vm-lkp-nex04-8G-10 ~/netperf-netperf-2.7.0# gcc hello.c -std=gnu89

Signed-off-by: Li Zhijian <zhijianx.li@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>