pkg/bpfcc-tools: remove i386 support
On i386, it complains:
----
tests/cc/test_usdt_args.cc:67:14: error: ‘parser’ was not declared in
this scope
     REQUIRE(!parser.parse(&arg));
----

Because test_usdt_args.cc tells it doesn't support i386:
(replace "#" with "$" to show the preprocessor directive)
----
$ifdef __aarch64__
    USDT::ArgumentParser_aarch64 parser("4@[x32,200]");
$elif __powerpc64__
    USDT::ArgumentParser_powerpc64 parser("4@-12(42)");
$elif __s390x__
    USDT::ArgumentParser_s390x parser("4@-12(%r42)");
$elif defined(__x86_64__)
    USDT::ArgumentParser_x64 parser("4@i%ra+1r");
$endif

USDT::Argument arg;

REQUIRE(!parser.parse(&arg));
----

Signed-off-by: Cao jin <jinx.cao@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>