distro/depends/autotest: fix Missing python library pexpect
fix the following issue:
```
wuhh@inn:/result/autotest/libvirt_test_api/vm-snb/debian-x86_64-2019-05-14.cgz/x86_64-rhel-7.6/gcc-7/da0c9ea146cbe92b832f1b0f694840ea8eb33cce/8$ cat autotest
2019-10-13 03:44:58 python2.7 client/autotest-local run libvirt_test_api
03:44:58 INFO | Writing results to /lkp/benchmarks/autotest/client/results/default
03:44:58 ERROR| Could not determine initlevel, assuming 2
03:44:59 INFO | START	----	----	timestamp=1570909499	localtime=Oct 13 03:44:59
03:44:59 INFO | 	START	libvirt_test_api.consumption	libvirt_test_api.consumption	timestamp=1570909499	localtime=Oct 13 03:44:59
03:44:59 ERROR| Exception escaping from test:
Traceback (most recent call last):
  File "/lkp/benchmarks/autotest/client/shared/test.py", line 378, in _exec
    _cherry_pick_call(self.initialize, *args, **dargs)
  File "/lkp/benchmarks/autotest/client/shared/test.py", line 738, in _cherry_pick_call
    return func(*p_args, **p_dargs)
  File "/lkp/benchmarks/autotest/client/tests/libvirt_test_api/libvirt_test_api.py", line 22, in initialize
    raise error.TestError("Missing python library pexpect. You have to "
TestError: Missing python library pexpect. You have to install the package python-pexpect or the equivalent for your distro
```

Signed-off-by: Zhou Hao <haox.a.zhou@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>