pack/ocfs2test: using unpack instead of install to install releated header
ocfs2test requires an old version(2.23) <sys/wait.h>, previously we install this
header via dpkg -i xxx.deb which wll not work for local user.
here we use unpack method to install this header and tell Makefile to search it

---------------
make[2]: Entering directory '/home/ocfs2test/ocfs2-test/programs/inline-data'
gcc -O2 -Wall -g       -MD -MP -MF ./.inline-data.d -o inline-data.o -c inline-data.c
inline-data.c: In function ‘sigchld_handler’:
inline-data.c:259:13: error: storage size of ‘status’ isn’t known        <========
  union wait status;
             ^~~~~~
inline-data.c:259:13: warning: unused variable ‘status’ [-Wunused-variable]
../../Postamble.make:40: recipe for target 'inline-data.o' failed
make[2]: *** [inline-data.o] Error 1
make[2]: Leaving directory '/home/ocfs2test/ocfs2-test/programs/inline-data'
../Postamble.make:54: recipe for target 'inline-data' failed
make[1]: *** [inline-data] Error 2
make[1]: Leaving directory '/home/ocfs2test/ocfs2-test/programs'
Postamble.make:54: recipe for target 'programs' failed
make: *** [programs] Error 2
---------------

Signed-off-by: Li Zhijian <zhijianx.li@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>