stats/leaking-addresses: fix "undefined method `gsub' for nil:NilClass (NoMethodError)"
the error was caused by "[2 6] inotify wd:29 ino:1ff sdev:1b mask:2 ignored_mask:0 fhandle-bytes:8 fhandle-type:fe f_handle:ff01000000000000",
have checked output file in all passed (have leaking-addresses.json) rt,
none of them has this error line, so here we ignore it, add [^\d] to avoid "[2 6]".

Signed-off-by: Carel Si <beibei.si@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>