autotest: Comment out the wrong test sparse
fix the following issue:
```
2019-11-07 06:20:12 python2.7 client/autotest-local run sparse
06:20:15 ERROR| child process failed
06:20:15 INFO |                 ERROR   sparse  sparse  timestamp=1573107615    localtime=Nov 07 06:20:15       Unhandled AutotestError: Unknown parameter: patches
  Traceback (most recent call last):
    File "/lkpaddon/lkp/benchmarks/autotest/client/job.py", line 513, in _runtest
      parallel.fork_waitfor(self.resultdir, pid)
    File "/lkpaddon/lkp/benchmarks/autotest/client/parallel.py", line 88, in fork_waitfor
      _check_for_subprocess_exception(tmp, pid)
    File "/lkpaddon/lkp/benchmarks/autotest/client/parallel.py", line 82, in _check_for_subprocess_exception
      raise e
  AutotestError: Unknown parameter: patches
```
The reason for the error is that there is a patch parameter in the control file in sparse, which is not recognized by autotest.
```
root@clear-lkp-30040/lkp/benchmarks/autotest/client/tests/sparse # cat control
job.run_test('sparse',
             base_tree='/usr/local/src/linux-2.6.14.tar.bz2',
             patches='/usr/local/src/patch-2.6.14-git6.bz2',
             config='http://ftp.kernel.org/pub/linux/kernel/people/mbligh/config/config.up')
```

Signed-off-by: Zhou Hao <haox.a.zhou@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>