lib/tests/kernel-selftests.sh: ignore subtest landlock
landlock depends on the new version libc6-dev:
--------------
In file included from common.h:14,
                 from fs_test.c:22:
fs_test.c: In function 'layout1_move_mount':
fs_test.c:1173:23: error: 'SYS_move_mount' undeclared (first use in this function); did you mean 'SYS_mount'?
  ASSERT_EQ(0, syscall(SYS_move_mount, AT_FDCWD, dir_s3d2, AT_FDCWD,))

$ grep -r move_mount /usr/include/x86_64-linux-gnu/
/usr/include/x86_64-linux-gnu/bits/syscall.h:#ifdef __NR_move_mount
/usr/include/x86_64-linux-gnu/bits/syscall.h:# define SYS_move_mount __NR_move_mount
--------------

Signed-off-by: Chen Rong <rong.a.chen@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>