jobs/autotest-part3.yaml: ignore iosched_bugs due to compile error
2019-10-08 02:13:48 python2.7 client/autotest-local run iosched_bugs
02:13:49 INFO | Writing results to /lkp/benchmarks/autotest/client/results/default
02:13:49 ERROR| Could not determine initlevel, assuming 2
02:13:49 INFO | START	----	----	timestamp=1570472029	localtime=Oct 08 02:13:49
02:13:49 INFO | 	START	iosched_bugs	iosched_bugs	timestamp=1570472029	localtime=Oct 08 02:13:49
02:13:49 ERROR| [stderr] /tmp/lkp/cc56Y0pq.o: In function `main':
02:13:49 ERROR| [stderr] dirty.c:(.text+0x114): undefined reference to `rdtsc'
02:13:49 ERROR| [stderr] dirty.c:(.text+0x124): undefined reference to `rdtsc'
02:13:49 ERROR| [stderr] collect2: error: ld returned 1 exit status
02:13:49 ERROR| [stderr] make: *** [dirty] Error 1
02:13:49 ERROR| Exception escaping from test:

Signed-off-by: Philip Li <philip.li@intel.com>