pack/mdadm-selftests: fix pack failed
To fix the following error info:

root@waimea /tmp/mdadm# make test
cc -Wall -Werror -Wstrict-prototypes -Wextra -Wno-unused-parameter -ggdb -DSendmail=\""/usr/sbin/sendmail -t"\" -DCONFFILE=\"/etc/mdadm.conf\" -DCONFFILE2=\"/etc/mdadm/mdadm.conf\" -DMAP_DIR=\"/run/mdadm\" -DMAP_FILE=\"map\" -DMDMON_DIR=\"/run/mdadm\" -DFAILED_SLOTS_DIR=\"/run/mdadm/failed-slots\" -DNO_COROSYNC -DNO_DLM -DVERSION=\"3.4-43-g1dcee1c\" -DVERS_DATE="\"06th April 2016\"" -DUSE_PTHREADS -DBINDIR=\"/sbin\"  -c -o raid6check.o raid6check.c
raid6check.c: In function 'manual_repair':
raid6check.c:267:4: error: this 'else' clause does not guard... [-Werror=misleading-indentation]
    else
    ^~~~
raid6check.c:269:5: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'else'
     printf("Repairing D(%d) and P\n", failed_data);
     ^~~~~~
cc1: all warnings being treated as errors
<builtin>: recipe for target 'raid6check.o' failed
make: *** [raid6check.o] Error 1
root@waimea /tmp/mdadm#

check the Makefile file:

renyl@bee:~/tmp/mdadm$ nl Makefile | tail -30
   257		if [ -f /etc/SuSE-release -o -n "$(SUSE)" ] ;then $(INSTALL) -D -m 755 systemd/SUSE-mdadm_env.sh $(DESTDIR)$(SYSTEMD_DIR)/../scripts/mdadm_env.sh ;fi

   258	uninstall:
   259		rm -f $(DESTDIR)$(MAN8DIR)/mdadm.8 $(DESTDIR)$(MAN8DIR)/mdmon.8 $(DESTDIR)$(MAN4DIR)/md.4 $(DESTDIR)$(MAN5DIR)/mdadm.conf.5 $(DESTDIR)$(BINDIR)/mdadm

   260	test: mdadm mdmon test_stripe swap_super raid6check                 <======
   261		@echo "Please run './test' as root"

   262	clean :
   263		rm -f mdadm mdmon $(OBJS) $(MON_OBJS) $(STATICOBJS) core *.man \
   264		mdadm.tcc mdadm.uclibc mdadm.static *.orig *.porig *.rej *.alt .merge_file_* \
   265		mdadm.Os mdadm.O2 mdmon.O2 \
   266		mdassemble mdassemble.static mdassemble.auto mdassemble.uclibc \
   267		mdassemble.klibc swap_super \
   268		init.cpio.gz mdadm.uclibc.static test_stripe raid6check raid6check.o mdmon \
   269		mdadm.8

   270	dist : clean
   271		./makedist

   272	testdist : everything-test clean
   273		./makedist test

   274	TAGS :
   275		etags *.h *.c

   276	DISTRO_MAKEFILE := $(wildcard distropkg/Makefile)
   277	ifdef DISTRO_MAKEFILE
   278	include $(DISTRO_MAKEFILE)
   279	endif
renyl@bee:~/tmp/mdadm$

could remove "raid6check" to workaround this issue.

why need to run "make test", not "make", can refer to this commit: 70570a47b0e995f00907ecb9f0a436a5f5359d77

one successful result_root:
renyl@inn:/result/pack/debian-x86_64-2016-08-31.cgz-mdadm-selftests/vm-lkp-nex04-8G/debian-x86_64-2016-08-31.cgz/x86_64-rhel-7.2/gcc-6/523d939ef98fd712632d93a5a2b588e477a7565e/4$ ll
total 84
-rw-rw-r-- 1 lkp      lkp    10 Oct 25 11:46 boot-time
-rw-rw-r-- 1 renyl    lkp   160 Oct 25 11:54 dmesg.json
-rw-rw-r-- 1 renyl    lkp 14064 Oct 25 11:54 dmesg.xz
-rwxrwxr-x 1 www-data lkp  3809 Oct 25 11:46 job.sh
-rw-rw-r-- 1 www-data lkp  3086 Oct 25 11:54 job.yaml
-rw-rw-r-- 1 renyl    lkp    49 Oct 25 11:54 kmsg.json
-rw-rw-r-- 1 renyl    lkp   149 Oct 25 11:54 matrix.json.gz
-rw-rw-r-- 1 lkp      lkp  5728 Oct 25 11:53 output
-rw-rw-r-- 1 lkp      lkp  4817 Oct 25 11:53 pack
-rw-rw-r-- 1 lkp      lkp  2300 Oct 25 11:46 qemu.time
-rw-rw-r-- 1 renyl    lkp   167 Oct 25 11:54 stats.json
-rw-rw-r-- 1 lkp      lkp  5666 Oct 25 11:53 stdout
-rw-rw-r-- 1 lkp      lkp  8257 Oct 25 11:53 umesg
renyl@inn:/result/pack/debian-x86_64-2016-08-31.cgz-mdadm-selftests/vm-lkp-nex04-8G/debian-x86_64-2016-08-31.cgz/x86_64-rhel-7.2/gcc-6/523d939ef98fd712632d93a5a2b588e477a7565e/4$ tail output
Fetched 70.0 MB in 19s (3644 kB/s)
Reading package lists...
install packages for lkp-dev: make automake gcc build-essential libtool patch git openssl ca-certificates rsync cpio wget libklibc-dev linux-libc-dev linux-libc-dev:i386 libc6-dev libc6-dev:i386
/lkp/renyl/src/sbin/pack -c -s /osimage/pkg/debian-x86_64-2016-08-31.cgz mdadm-selftests
timeout 60m git clone -q git://git.neil.brown.name/mdadm.git mdadm
sending incremental file list
mdadm-selftests-x86_64.cgz

sent 555,952 bytes  received 35 bytes  1,111,974.00 bytes/sec
total size is 555,716  speedup is 1.00
renyl@inn:/result/pack/debian-x86_64-2016-08-31.cgz-mdadm-selftests/vm-lkp-nex04-8G/debian-x86_64-2016-08-31.cgz/x86_64-rhel-7.2/gcc-6/523d939ef98fd712632d93a5a2b588e477a7565e/4$

detailed info can refer to:
https://jira01.devtools.intel.com/browse/OLT-1388

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>