kernel_selftests: add missing dependency package
To fix the following error info:

renyl@inn:/result/kernel_selftests/defaults/vm-lkp-a08/debian-x86_64-2016-08-31.cgz/x86_64-rhel-7.2/gcc-6/v4.8-rc6/6$ cat stderr | head -5
validate_cap.c:1:20: fatal error: cap-ng.h: No such file or directory <======
 #include <cap-ng.h>
                    ^
compilation terminated.
make: *** [validate_cap] Error 1
renyl@inn:/result/kernel_selftests/defaults/vm-lkp-a08/debian-x86_64-2016-08-31.cgz/x86_64-rhel-7.2/gcc-6/v4.8-rc6/6$

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>