distro/depends: add missing dependency package for xfstests-dev
To fix the following error info:

root@waimea /tmp/xfstests-dev# make
./configure \
                --libexecdir=/usr/lib
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gmake... no
checking for make... /usr/bin/make
checking for glibtool... no
checking for libtool... no  <======

FATAL ERROR: libtool does not seem to be installed.
xfstests cannot be built without a working GNU libtool installation.
Makefile:83: recipe for target 'include/builddefs' failed
make: *** [include/builddefs] Error 1
root@waimea /tmp/xfstests-dev#

detailed info can refer to: https://jira01.devtools.intel.com/browse/OLT-1403

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>