distro/depends: add missing package for netperf
To fix the following error info:
=======================================================================
==> /tmp/stderr <==
configure: error: in `/tmp/netperf-2.6.0':
configure: error: C compiler cannot create executables
See `config.log' for more details

==> /tmp/stdout <==
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc-4.9
checking whether the C compiler works... no

==> /tmp/stderr <==
make: *** No targets specified and no makefile found.  Stop.
=======================================================================

also try to use the default gcc-5 to compile netperf, will get some error info below:

=======================================================================
gcc     -o netperf netperf.o netlib.o netsh.o nettest_bsd.o nettest_dlpi.o nettest_unix.o nettest_xti.o nettest_sctp.o nettest_sdp.o nettest_omni.o net_uuid.o dscp.o netcpu_procstat.o netrt_rtnetlink.o netdrv_ethtool.o netslot_linux.o netsys_linux.o netsec_linux.o  -ldl -lsctp -lm
Makefile:321: recipe for target 'netperf' failed
make[3]: Leaving directory '/tmp/netperf-2.6.0/src'
Makefile:374: recipe for target 'all-recursive' failed
make[2]: Leaving directory '/tmp/netperf-2.6.0/src'
Makefile:280: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/tmp/netperf-2.6.0'
Makefile:216: recipe for target 'all' failed
nettest_unix.o: In function `recv_stream_stream':
nettest_unix.c:(.text+0xce1): warning: the use of `tempnam' is dangerous, better use `mkstemp'
netlib.o: In function `demo_interval_final':
netlib.c:(.text+0x3eb4): undefined reference to `demo_interval_display'
netlib.o: In function `demo_stream_interval':
netlib.c:(.text+0x3eda): undefined reference to `demo_interval_tick'
netlib.o: In function `demo_rr_interval':
netlib.c:(.text+0x3f58): undefined reference to `demo_interval_tick'
nettest_omni.o: In function `send_omni_inner':
nettest_omni.c:(.text+0x7da2): undefined reference to `demo_interval_tick'
nettest_omni.c:(.text+0x7db9): undefined reference to `demo_interval_tick'
nettest_omni.c:(.text+0x7de2): undefined reference to `demo_interval_tick'
nettest_omni.o:nettest_omni.c:(.text+0x7dee): more undefined references to `demo_interval_tick' follow
collect2: error: ld returned 1 exit status
make[3]: *** [netperf] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
=======================================================================

thus use gcc-4.9 can compile it successfully, so add gcc-4.9 dependency package.

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>