nvml: don't checkout specified source version
to use latest benchmark source.
fix running error after switch to latest source:
		stderr: /usr/bin/ld: ../../../../src/tools/../../src/../src/nondebug/libpmemcommon.a(libpmemcommon_all.o): in function `pmem2_badblock_context_new':
		stderr: (.text+0xcad5): undefined reference to `pmem2_region_namespace'
		stderr: /usr/bin/ld: ../../../../src/tools/../../src/../src/nondebug/libpmemcommon.a(libpmemcommon_all.o): in function `pmem2_source_device_usc':
		stderr: (.text+0xd49c): undefined reference to `pmem2_region_namespace'
		stderr: /usr/bin/ld: ../../../../src/tools/../../src/../src/nondebug/libpmemcommon.a(libpmemcommon_all.o): in function `pmem2_source_device_id':
		stderr: (.text+0xd621): undefined reference to `pmem2_region_namespace'
		stderr: clang: error: linker command failed with exit code 1 (use -v to see invocation)
		stderr: make[2]: *** [../../../../src/tools/Makefile.inc:287: pmemspoil.static-nondebug] Error 1
		stderr: make[1]: *** [Makefile:59: pmemspoil] Error 2

Signed-off-by: Xia Hui <hui.xia@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>