stats/pmbench: Fix exception for pure read/write mode
If read ratio == 0 or 100, the following exception will be reported,

/lkp/yhuang/src/stats/pmbench:63:in `block (2 levels) in <main>': undefined method `/' for nil:NilClass (NoMethodError)
        from /lkp/yhuang/src/stats/pmbench:62:in `each'
        from /lkp/yhuang/src/stats/pmbench:62:in `block in <main>'
        from /lkp/yhuang/src/stats/pmbench:61:in `each'
        from /lkp/yhuang/src/stats/pmbench:61:in `<main>'

Because some data has no opportunity to be initialized.  Fix this via
ignoring unreasonable output for pure read/write mode.

Signed-off-by: Huang Ying <ying.huang@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>