include/kernel_selftests: fix kernel_selftests.bpf.test_lwt_seg6local.fail
fix the following issue
------
selftests: bpf: test_lwt_seg6local.sh
========================================
RTNETLINK answers: Operation not supported
selftests: test_lwt_seg6local [FAILED]
not ok 1..24 selftests: bpf: test_lwt_seg6local.sh [FAIL]
------
the test failed when it sets IPv6 address, it needs to enable IPV6_SEG6_LWTUNNEL and LWTUNNEL.
BTW: after enable corresponding config, the test still failed, it is expected.
------
selftests: bpf: test_lwt_seg6local.sh
========================================
Error: argument "End.BPF" is wrong: "action" value is invalid

selftests: test_lwt_seg6local [FAILED]
not ok 1..24 selftests: bpf: test_lwt_seg6local.sh [FAIL]
------
commit c99a84eac026f404457810f5253220bab17ac213 introduced a new seg6local action End.BPF with the corresponding new BPF program type BPF_PROG_TYPE_LWT_SEG6LOCAL.
But BPF_PROG_TYPE_LWT_SEG6LOCA has not been added to libbpf.c, it is missing right now.

Signed-off-by: Liu Yiding <liuyd.fnst@cn.fujitsu.com>

Signed-off-by: Philip Li <philip.li@intel.com>