tests/autotest: fix SyntaxError: Missing parentheses in call to 'print'
fix the following issue:
```
2019-10-09 18:19:51 python2.7 client/autotest-local run compilebench
18:19:51 ERROR| Exception escaping from test:
...
  stderr:
    File "/lkp/benchmarks/autotest/client/tmp/compilebench/src/compilebench", line 459
      print "no runs for %s" % tag
                           ^
  SyntaxError: Missing parentheses in call to 'print'. Did you mean print("no runs for %s" % tag)?
```

Signed-off-by: Zhou Hao <haox.a.zhou@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>