pkg/fio: fix fio make error
[error]
crc/../os/os-linux.h:127:19: error: static declaration of ‘gettid’
follows non-static declaratio

fio latest has fix this problem, but we use fio 3.12 version,
so we need this patch to fix this problem.

Signed-off-by: Wei Jihui <weijihuiall@163.com>