build-dpdk: fix ld issue
To fix the following error info:

/usr/lib/x86_64-linux-gnu/libmvec_nonshared.a(svml_finite_alias.oS): In function `_ZGVbN2v___log_finite':
(.text+0x0): multiple definition of `_ZGVbN2v___log_finite'
/usr/lib/x86_64-linux-gnu/libmvec_nonshared.a(svml_finite_alias.oS):(.text+0x0): first defined here
/usr/lib/x86_64-linux-gnu/libmvec_nonshared.a(svml_finite_alias.oS): In function `_ZGVcN4v___log_finite':
(.text+0x10): multiple definition of `_ZGVcN4v___log_finite'
/usr/lib/x86_64-linux-gnu/libmvec_nonshared.a(svml_finite_alias.oS):(.text+0x10): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [app] Error 2
make[2]: *** [test-acl] Error 2
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [test] Error 2

when gcc on ld stage, it will find libmvec_nonshared.a file, so can not remove it, just link to another more popular .so library.
and actually dpdk fully do not depend on libmvec_nonshared.a library.

detailed info can check: https://jira01.devtools.intel.com/browse/OLT-881

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>