lib/matrix.rb: add a sanity check for empty array
To fix the following error info:
2017-02-23 09:21:29.344361500 [lkp process-unite-queue 46816 dump_exception] ERROR -- /lkp/lkp/src/lib/statistics.rb:18:in `average': undefined method `/' for nil:NilClass (NoMethodError)
2017-02-23 09:21:29.344364500 [lkp process-unite-queue 46816 dump_exception] ERROR --   from /lkp/lkp/src/lib/matrix.rb:131:in `block in matrix_average'
2017-02-23 09:21:29.344365500 [lkp process-unite-queue 46816 dump_exception] ERROR --   from /lkp/lkp/src/lib/matrix.rb:131:in `each'
2017-02-23 09:21:29.344379500 [lkp process-unite-queue 46816 dump_exception] ERROR --   from /lkp/lkp/src/lib/matrix.rb:131:in `matrix_average'
2017-02-23 09:21:29.344380500 [lkp process-unite-queue 46816 dump_exception] ERROR --   from /lkp/lkp/src/lib/matrix.rb:203:in `unite_to'
2017-02-23 09:21:29.344381500 [lkp process-unite-queue 46816 dump_exception] ERROR --   from /lkp/lkp/src/lib/matrix.rb:351:in `unite_stats'
2017-02-23 09:21:29.344385500 [lkp process-unite-queue 46816 dump_exception] ERROR --   from /lkp/lkp/src/lib/unite.rb:997:in `unite_result'
2017-02-23 09:21:29.344386500 [lkp process-unite-queue 46816 dump_exception] ERROR --   from /lkp/lkp/src/lib/unite.rb:1100:in `unite_one'
2017-02-23 09:21:29.344392500 [lkp process-unite-queue 46816 dump_exception] ERROR --   from /lkp/lkp/src/sbin/process-unite-queue:33:in `block (2 levels) in main_loop'
2017-02-23 09:21:29.344393500 [lkp process-unite-queue 46816 dump_exception] ERROR --   from /lkp/lkp/src/sbin/process-unite-queue:32:in `each'
2017-02-23 09:21:29.344397500 [lkp process-unite-queue 46816 dump_exception] ERROR --   from /lkp/lkp/src/sbin/process-unite-queue:32:in `block in main_loop'
2017-02-23 09:21:29.344398500 [lkp process-unite-queue 46816 dump_exception] ERROR --   from /lkp/lkp/src/sbin/process-unite-queue:26:in `loop'
2017-02-23 09:21:29.344399500 [lkp process-unite-queue 46816 dump_exception] ERROR --   from /lkp/lkp/src/sbin/process-unite-queue:26:in `main_loop'
2017-02-23 09:21:29.344402500 [lkp process-unite-queue 46816 dump_exception] ERROR --   from /lkp/lkp/src/sbin/process-unite-queue:45:in `<main>'

not root casue the reason.

unite_to does call matrix_fill_missing_zeros to fill null value, so the array should be not empty.

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>