kernel-selftests: Fix userfaultfd.c:1384:37: error: 'MADV_PAGEOUT' undeclare
glibc <= 2.28 doesn't provide MADV_PAGEOUT

  HOSTCC  scripts/basic/fixdep
  WRAP    arch/x86/include/generated/uapi/asm/bpf_perf_event.h
  WRAP    arch/x86/include/generated/uapi/asm/errno.h
  WRAP    arch/x86/include/generated/uapi/asm/fcntl.h
  WRAP    arch/x86/include/generated/uapi/asm/ioctl.h
userfaultfd.c: In function userfaultfd_pagemap_test
userfaultfd.c:1384:37: error: MADV_PAGEOUT undeclared
(first use in this function); did you mean MADV_RANDOM?
  if (madvise(area_dst, test_pgsize, MADV_PAGEOUT))
                                     ^~~~~~~~~~~~
                                     MADV_RANDOM
userfaultfd.c:1384:37: note: each undeclared identifier is reported only
once for each function it appears in
  WRAP    arch/x86/include/generated/uapi/asm/ioctls.h
  WRAP    arch/x86/include/generated/uapi/asm/ipcbuf.h
  WRAP    arch/x86/include/generated/uapi/asm/param.h

add new glibc add this macro, below is a partial difference between v2.28 and v2.32:
 /* Advice to `madvise'.  */
 #ifdef __USE_MISC
 # define MADV_NORMAL  0/* No further special treatment.  */
@@ -93,6 +87,8 @@
 # d		efine MADV_DODUMP  17/* Clear the MADV_DONTDUMP flag.
*/
 # define M		ADV_WIPEONFORK  18/* Zero memory on fork, child
only.  */
 # define MA	DV_KEEPONFORK  19/* Undo MADV_WIPEONFORK.  */
+# define MADV_COLD     	   20/* Deactivate these pages.  */
+# define MADV_PAGEOUT     21/* R		eclaim these pages.  */
 # define MADV_HWPOISON  100/* Poison a page 		for testing.  */
 #endif

Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>
Signed-off-by: Philip Li <philip.li@intel.com>