distro/depends/oltp: install MySQL 5.7
fix the following issue
------
2018-09-26  6:31:22 139783461855808 [ERROR] /usr/sbin/mysqld: unknown option '--initialize'
------
we initialize mysql in setup/mysql-setup
------
/usr/sbin/mysqld --initialize
------
option "--initizalize" is introduced in MySQL 5.7.7
------
Prior to MySQL 5.7.7, Windows distributions include a data directory with prebuilt tables in the mysql database
------
this commit install mariadb-server to fix some error
------
commit de50954c55d0be7a121c40de0c2c4da725c9518f
Author: leishaoting <leist.fnst@cn.fujitsu.com>
Date:   Tue Aug 21 10:59:01 2018 +0800

    lib/bootstrap.sh: mount /var/lib/mysql/ for mysql

    fix the issue
    ---------------
    ERROR: There's not enough space in /var/lib/mysql/
    ---------------
------
but mariadb-server conflicts with MySQL 5.7, when we have installed MySQL 5.7, we don't trigger out below ERROR
------
ERROR: There's not enough space in /var/lib/mysql/
------
so we could remove mariadb-server

Signed-off-by: Liu Yiding <liuyd.fnst@cn.fujitsu.com>

Signed-off-by: Philip Li <philip.li@intel.com>