autotest: fixup missing automake
12:19:31 ERROR| Exception escaping from test:
Traceback (most recent call last):
  File "/lkp/benchmarks/autotest/client/shared/test.py", line 387, in _exec
    *p_args, **p_dargs)
  File "/lkp/benchmarks/autotest/client/shared/utils.py", line 865, in update_version
    install(*args, **dargs)
  File "/lkp/benchmarks/autotest/client/tests/reaim/reaim.py", line 22, in setup
    os_dep.commands('autoconf', 'automake', 'libtoolize')
  File "/lkp/benchmarks/autotest/client/os_dep.py", line 23, in commands
    results.append(command(cmd))
  File "/lkp/benchmarks/autotest/client/os_dep.py", line 17, in command
    raise ValueError('Missing command: %s' % cmd)
ValueError: Missing command: automake

Signed-off-by: Fengguang Wu <fengguang.wu@intel.com>