piglit/quick-223: fix cannot stat /tmp/lkp/piglit-results/results.json.bz2
fix the following error:
```
suy@inn$ cd
/result/piglit/quick-223/lkp-skl-d01/debian-x86_64-2018-04-03.cgz/x86_64-rhel-7.6/gcc-7/1c163f4c7b3f621efff9b28a47abb36f7378d783/9
9@inn$ cat stderr
......
FileNotFoundError: [Errno 2] No such file or directory:
'/tmp/lkp/piglit-results/results.json.bz2'
mv: cannot stat '/tmp/lkp/piglit-results/results.json.bz2': No such file
or directory
```

The reason for the error is that some of the test paths specified in
quick-233 do not exist:
```
root@lkp-skl-d01 /lkp/benchmarks/piglit# find . -name
"*forward-compatible-bityes*"
root@lkp-skl-d01 /lkp/benchmarks/piglit#
```

After removing these tests, this problem was solved:
```
20@inn$ pwd
/result/piglit/quick-223/lkp-skl-d01/debian-x86_64-2018-04-03.cgz/x86_64-rhel-7.6/gcc-7/v5.1-rc1/20
20@inn$ cat stderr

xinit: connection to X server lost

waiting for X server to shut down
20@inn$
```

Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>
Signed-off-by: Philip Li <philip.li@intel.com>