sbin/pack: fix do package failed
[why]
  pack/quiet and pack/default have been removed in commit:
    - 33efa9c7bf193b44f72f757f494280ded113a786
  but in script sbin/pack, the script sourced them and called functions:
    - strip_object_files
    - pack_pkg

  it lead to failure for referenced non-exist files with following error msg:

    /c/lkp-tests/sbin/pack: line 92: /c/lkp-tests/pack/quiet: No such file or directory
    /c/lkp-tests/sbin/pack: line 93: /c/lkp-tests/pack/default: No such file or directory
    make: Entering directory '/c/lkp-tests/bin/event'
    gcc    -c -o wakeup.o wakeup.c
    gcc  -static -o wakeup wakeup.o
    rm -f wakeup.o
    strip wakeup
    make: Leaving directory '/home/c/lkp-tests/bin/event'
    /c/lkp-tests/sbin/pack: line 114: strip_object_files: command not found
    /c/lkp-tests/sbin/pack: line 118: pack_pkg: command not found
    result: /srv/initrd/lkp/lkp-aarch64.cgz
    error: cannot pull with rebase: You have unstaged changes.
    error: please commit or stash them.

[how]
  kill invalid reverence;
  use function in pack/lkp-src instead: pack

Signed-off-by: Luan Shengde <shdluan@163.com>