repo/linux/hnaz-linux-mm: allow test master branch
We need to update the branch to avoid the below issue:
Re: [PATCH] mm: gup: remove FOLL_SPLIT
---------------
> url:    https://github.com/0day-ci/linux/commits/Yang-Shi/mm-gup-remove-FOLL_SPLIT/20210330-034042
> base:   https://github.com/hnaz/linux-mm master
...
> All errors (new ones prefixed by >>):
>
>     arch/s390/mm/gmap.c: In function 'thp_split_mm':
>>> arch/s390/mm/gmap.c:2498:27: error: 'FOLL_SPLIT' undeclared (first use in this function); did you mean 'FOLL_PIN'?
>      2498 |    follow_page(vma, addr, FOLL_SPLIT);
>           |                           ^~~~~~~~~~
>           |                           FOLL_PIN
>     arch/s390/mm/gmap.c:2498:27: note: each undeclared identifier is reported only once for each function it appears in
>
>
> vim +2498 arch/s390/mm/gmap.c

There appears to be an imperfection in this 0day testing system, because (just as the patch
says), commit ba925fa35057a062ac98c3e8138b013ce4ce351c ("s390/gmap: improve THP splitting"),
July 29, 2020, removes the above use of FOLL_SPLIT.

And "git grep", just to be sure, shows it is not there in today's linux.git. So I guess the
https://github.com/0day-ci/linux repo needs a better way to stay in sync?
---------------

Signed-off-by: Chen Rong <rong.a.chen@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>