distro/depends/autotest: fix Missing required command nmap
fix the following issue:
```
run-job /lkp/jobs/scheduled/vm-snb-a1f53fe6932e/autotest-libvirt_test_api-debian-x86_64-2019-05-14.cgz-da0c9ea146cbe92b832f-20191023-66393-1bysxru-0.yaml
/usr/bin/wget -q --timeout=1800 --tries=1 --local-encoding=UTF-8 http://inn:80/~zhouhao/cgi-bin/lkp-jobfile-append-var?job_file=/lkp/jobs/scheduled/vm-snb-a1f53fe6932e/autotest-libvirt
_test_api-debian-x86_64-2019-05-14.cgz-da0c9ea146cbe92b832f-20191023-66393-1bysxru-0.yaml&job_state=running -O /dev/null
target ucode:
2019-10-23 14:12:46 python2.7 client/autotest-local run libvirt_test_api
14:12:46 INFO | Writing results to /lkp/benchmarks/autotest/client/results/default
14:12:46 INFO | START   ----    ----    timestamp=1571811166    localtime=Oct 23 14:12:46
14:12:46 INFO |         START   libvirt_test_api.consumption    libvirt_test_api.consumption    timestamp=1571811166    localtime=Oct 23 14:12:46
14:12:46 ERROR| Exception escaping from test:
Traceback (most recent call last):
  File "/lkp/benchmarks/autotest/client/shared/test.py", line 378, in _exec
    _cherry_pick_call(self.initialize, *args, **dargs)
  File "/lkp/benchmarks/autotest/client/shared/test.py", line 738, in _cherry_pick_call
    return func(*p_args, **p_dargs)
  File "/lkp/benchmarks/autotest/client/tests/libvirt_test_api/libvirt_test_api.py", line 28, in initialize
    raise error.TestError("Missing required command nmap. You have to"
TestError: Missing required command nmap. You have toinstall the package nmap or the equivalentfor your distro
14:12:46 ERROR| child process failed
```
Signed-off-by: Zhou Hao <haox.a.zhou@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>