piglit/quick-245: fix cannot stat /tmp/lkp/piglit-results/results.json.bz2
fix the following error:
```
wuhh@inn:~$ cat
/result/piglit/quick-245/lkp-skl-d01/debian-x86_64-2018-04-03.cgz/x86_64-rhel-7.6/gcc-7/v5.1-rc1/1/stderr
......
FileNotFoundError: [Errno 2] No such file or directory:
'/tmp/lkp/piglit-results/results.json.bz2'
mv: cannot stat '/tmp/lkp/piglit-results/results.json.bz2': No such file
or directory
```

The reason for the error is that some of the test paths specified in
quick-245 do not exist.

After removing these tests, this problem was solved:
```
6@inn$ pwd
/result/piglit/quick-245/lkp-skl-d01/debian-x86_64-2018-04-03.cgz/x86_64-rhel-7.6/gcc-7/9e98c678c2d6ae3a17cb2de55d17f69dddaa231b/6
6@inn$ cat stderr

xinit: connection to X server lost

waiting for X server to shut down
6@inn$
```

Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>
Signed-off-by: Philip Li <philip.li@intel.com>