distro/depends: add missing dependency package for chromeswap
To fix the following error info:
renyl@inn:/result/chromeswap/1-uniform-1-0.5-performance/lkp-hsw-ep4/debian-x86_64-2016-08-31.cgz/x86_64-rhel/gcc-6/e64fc91483522881d92d912130507fdbef63f913/0$ cat stderr
Traceback (most recent call last):
  File "/lkp/benchmarks/chromeswap/platform_CompressedSwapPerf.py", line 7, in <module>
    import logging, numpy, os, shutil, socket
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: libblas.so.3: cannot open shared object file: No such file or directory
renyl@inn:/result/chromeswap/1-uniform-1-0.5-performance/lkp-hsw-ep4/debian-x86_64-2016-08-31.cgz/x86_64-rhel/gcc-6/e64fc91483522881d92d912130507fdbef63f913/0$

Reported-by: Lu Aaron <aaron.lu@intel.com>
Reviewed-by: Fengguang Wu <fengguang.wu@intel.com>
Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>