distro/depends: add missing package for vm-scalability
To fix the following error info:

==> /tmp/stderr <==
usemem.c: In function 'do_unit':
usemem.c:441:18: warning: variable 'd' set but not used [-Wunused-but-set-variable]
    volatile long d;
                  ^
usemem.c: In function 'main':
usemem.c:858:18: warning: variable 'ptr' set but not used [-Wunused-but-set-variable]
   unsigned char *ptr;
                  ^~~
usemem_migrate.c:8:20: fatal error: numaif.h: No such file or directory  <======
 #include <numaif.h>
                    ^
compilation terminated.
make: *** [usemem_migrate] Error 1

root@waimea ~# dpkg -L libnuma-dev
/.
/usr
/usr/include
/usr/include/numaif.h  <======
/usr/include/numa.h
/usr/include/numacompat1.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libnuma.a
/usr/share
...
root@waimea ~#

Cc: Aaron Lu <aaron.lu@intel.com>
Cc: Fengguang Wu <fengguang.wu@intel.com>
Acked-by: Fengguang Wu <fengguang.wu@intel.com>
Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>