distro/installer/clear: add clear install helper
Looks we need to add mapping from debian package to clear bundle
like:
||debian || clear||
| make   | c-basic |
| gcc    | c-basic |

know issues:
root@clear-lkp /home/lizhijian/lkp-tests # lkp install jobs/idle.yaml
Use: /home/lizhijian/lkp-tests/distro/installer/clear install bc gawk gzip kmod time automake bison bsdtar build-essential bzip2 ca-certificates cpio fakeroot flex gcc git libc6-dev libc6-dev:i386 libklibc-dev libtool linux-libc-dev linux-libc-dev:i386 linux-perf make openssl patch rsync ruby ruby-dev wget
nothing to add, exiting now
gawk bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
nothing to add, exiting now
kmod bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
time bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
automake bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
bison bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
bsdtar bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
build-essential bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
bzip2 bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
ca-certificates bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
nothing to add, exiting now
fakeroot bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
flex bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
gcc bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
nothing to add, exiting now
libc6-dev bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
libc6-dev:i386 bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
libklibc-dev bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
libtool bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
linux-libc-dev bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
linux-libc-dev:i386 bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
linux-perf bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
make bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
nothing to add, exiting now
nothing to add, exiting now
rsync bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
ruby bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
ruby-dev bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
wget bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
Cannot install some packages in /home/lizhijian/lkp-tests/distro/depends/lkp

Signed-off-by: Li Zhijian <zhijianx.li@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>