autotest: comment out error test
fix the following issue:
```
NameError: invalid file /lkpaddon/lkp/benchmarks/autotest/client/tests/btreplay/blktrace-git-latest.tar.gz to cat to command tar xvf - 2>/dev/null
```

The reason for the error is that the autotest test-related code did not generate the blktrace-git-latest.tar.gz file in the specified path.
```
root@clear-lkp-30040/lkp/benchmarks/autotest/client/tests/btreplay # ls
btreplay.py  btreplay.pyc  control  Makefile.patch
```
Since the code has not been updated all the year round, comment out the wrong test.

Signed-off-by: Zhou Hao <haox.a.zhou@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>