setup/setup-linkbench: set mysql max_connections
set mysql max_connections to a large enough(greater than 2*nr_cpu) number.

fix the following issue
1. Too many connections
--------------------
ERROR 2020-06-11 16:10:08,889 [Thread-39]: error connecting to database:
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Too many connections
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
---------------------

2.
--------------------
stderr: mysqladmin: connect to server at 'localhost' failed
stderr: error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")'
stderr: Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
stderr: ERROR 1290 (HY000) at line 35: The MariaDB server is running with the --skip-grant-tables option so it cannot execute this statement
--------------------

Signed-off-by: MaXinjian <max.xinjian@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>