lib/tests/kernel-selftests.sh: ignore runqslower as a workaound
Since commit 9c01546d26d "tools/bpf: Add runqslower tool to tools/bpf"

Subtest bpf failed during build tools bpf.
------
make[1]: Entering directory '/usr/src/perf_selftests-x86_64-rhel-7.6-9c01546d26d28cf57341d8380ba900bf68e26b18/tools/bpf/runqslower'
Makefile:18: *** "Can't detect kernel BTF, use VMLINUX_BTF to specify it explicitly"
------

Need enable CONFIG_DEBUG_INFO_BTF to build BTF, but runqslower still build failed after
enable VMLINUX_BTF.
------
.output/vmlinux.h:9006:25: error: array has incomplete element type 'struct cyc2ns_data'
        struct cyc2ns_data data[2];
                               ^
.output/vmlinux.h:3669:8: note: forward declaration of 'struct cyc2ns_data'
struct cyc2ns_data;
       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Makefile:56: recipe for target '.output/runqslower.bpf.o' failed
make[1]: *** [.output/runqslower.bpf.o] Error 1
------

Ignore runqslower firstly. Otherwise all bpf test hang on.

Signed-off-by: Liu Yiding <yidingx.liu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>