kernel_selftests: add missing dependency package
To fix the following error info:

==> /tmp/stdout <==
  LD       gpio-event-mon-in.o
make[2]: Leaving directory '/usr/src/linux-selftests--0c744ea4f77d72b3dcebb7a8f2684633ec79be88/tools/gpio'
  LINK     gpio-event-mon
make[1]: Leaving directory '/usr/src/linux-selftests--0c744ea4f77d72b3dcebb7a8f2684633ec79be88/tools/gpio'
gcc -O2 -g -std=gnu99 -Wall -I../../../../usr/include/    gpio-mockup-chardev.c ../../../gpio/gpio-utils.o ../../../../usr/include/linux/gpio.h  -lmount -I/usr/include/libmount -o gpio-mockup-chardev

==> /tmp/stderr <==
gpio-mockup-chardev.c:21:22: fatal error: libmount.h: No such file or directory
 #include <libmount.h>
                      ^
compilation terminated.
make: *** [gpio-mockup-chardev] Error 1

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>