lib/matrix.rb: fix "46:in `matrix_fill_missing_zeros': undefined method `size' for nil:NilClass"
/lkp-src/lib/matrix.rb:46:in `matrix_fill_missing_zeros': undefined method `size' for nil:NilClass (NoMethodError)
	from /lkp-src/lib/matrix.rb:258:in `unite_to'

This happens when rm-path last rt, that all stats are removed
by the time to call matrix_fill_missing_zeros

Signed-off-by: Philip Li <philip.li@intel.com>