tests/xfstest: fix "'raw.img' is too small to make a usable filesystem" for btrfs
This error is because the maintainer no longer forcing mixed block
group for small filesystem. While the minimal size calculation is
still based on mixed block group.

Only btrfs need to add -M.

related link: https://github.com/kdave/btrfs-progs/issues/70
related patch: "Btrfs-progs: Do not force mixed block group creation unless '-M' option is specified"

before:
    ERROR: 'raw.img' is too small to make a usable filesystem
    ERROR: minimum size for each btrfs device is 114294784

after:
/result/xfstests/4HDD-btrfs-generic-logdev-ucode=0xe2/lkp-skl-d06/debian-10.4-x86_64-20200603.cgz/x86_64-$
    {
      "xfstests.generic.487.skip": [
        1
      ]
    }

Signed-off-by: Carel Si <beibei.si@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>