stats/build-pkg.rb: skip the errir_id processed by rpmbuild failed
Some software will rpmbuild themselves when compiling.
However, it will process a error id that include random directory.
The error id is useless, but because random directory will keep triggering bisect.
So skip it.

example:
error: Bad exit status from /var/tmp/rpm-tmp.uTWszm (%install)
                                               ^ random directory

Signed-off-by: Lin Jiaxin <ljx.joe@qq.com>