tests/build-dpdk: workaround to avoid fail to compile kernel
To fix the following error info:

renyl@inn:/result/build-dpdk/x86_64-native-linuxapp-gcc/b562e44f507e863c6792946e4e1b1449fbbac85d/gcc-5/05255e9d259e2ac10a4eba3caaa00c314a007a2d/0$ cat output  | tail -49
#
# configuration written to .config
#
2016-11-02 18:22:22 make -j 2 prepare
scripts/kconfig/conf  --silentoldconfig Kconfig
  SYSTBL  arch/x86/entry/syscalls/../../include/generated/asm/syscalls_32.h
  HOSTCC  scripts/basic/bin2c
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/asm/unistd_32_ia32.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/asm/unistd_64_x32.h
  SYSTBL  arch/x86/entry/syscalls/../../include/generated/asm/syscalls_64.h
  HYPERCALLS arch/x86/entry/syscalls/../../include/generated/asm/xen-hypercalls.h
  CHK     include/config/kernel.release
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_32.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_64.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_x32.h
  WRAP    arch/x86/include/generated/asm/clkdev.h
  WRAP    arch/x86/include/generated/asm/cputime.h
  WRAP    arch/x86/include/generated/asm/dma-contiguous.h
  WRAP    arch/x86/include/generated/asm/early_ioremap.h
  WRAP    arch/x86/include/generated/asm/mcs_spinlock.h
  WRAP    arch/x86/include/generated/asm/mm-arch-hooks.h
  CHK     include/generated/uapi/linux/version.h
  UPD     include/generated/uapi/linux/version.h
  HOSTCC  arch/x86/tools/relocs_32.o
  UPD     include/config/kernel.release
  HOSTCC  arch/x86/tools/relocs_64.o
  CHK     include/generated/utsrelease.h
  UPD     include/generated/utsrelease.h
  HOSTCC  arch/x86/tools/relocs_common.o
  HOSTLD  arch/x86/tools/relocs
  AS      arch/x86/purgatory/stack.o
  CC      arch/x86/purgatory/purgatory.o
  AS      arch/x86/purgatory/setup-x86_64.o
  CC      arch/x86/purgatory/sha256.o
  AS      arch/x86/purgatory/entry64.o
  CC      arch/x86/purgatory/string.o
  LD      arch/x86/purgatory/purgatory.ro
  BIN2C   arch/x86/purgatory/kexec-purgatory.c
  CHK     include/generated/timeconst.h
  CC      kernel/bounds.s
Kbuild:44: recipe for target 'kernel/bounds.s' failed
  UPD     include/generated/timeconst.h
Makefile:993: recipe for target 'prepare0' failed

==> /tmp/stderr <==
make prepare failed
  /lkp/lkp/src/lib/debug.sh:7: die
  /lkp/lkp/src/tests/build-dpdk:60: main
  :0:
renyl@inn:/result/build-dpdk/x86_64-native-linuxapp-gcc/b562e44f507e863c6792946e4e1b1449fbbac85d/gcc-5/05255e9d259e2ac10a4eba3caaa00c314a007a2d/0$

further check, the error info like below:

root@vm-lkp-nex04-8G-9 /build/linux/src# make prepare
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CHK     include/generated/timeconst.h
  CC      kernel/bounds.s
kernel/bounds.c:1:0: error: code model kernel does not support PIC mode              <======
 /*
Kbuild:44: recipe for target 'kernel/bounds.s' failed
make[1]: *** [kernel/bounds.s] Error 1
Makefile:993: recipe for target 'prepare0' failed
make: *** [prepare0] Error 2
root@vm-lkp-nex04-8G-9 /build/linux/src#

google that error info, and find this article: (https://bugs.gentoo.org/show_bug.cgi?id=584014)
" Gcc 6.1 with use pie enable add -fPIE and -pie as default. The kernel code don't compile well it. "

thus go to check the gcc version:
root@vm-lkp-nex04-8G-9 /tmp/lkp/make-stderr# which gcc
/usr/bin/gcc
root@vm-lkp-nex04-8G-9 /tmp/lkp/make-stderr# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.2.0-10' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6
+--program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug
+--enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo
+--with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64
+--with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu
+--host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.2.0 20161027 (Debian 6.2.0-10)   <======
root@vm-lkp-nex04-8G-9 /tmp/lkp/make-stderr#

due to specify the gcc version in job.yaml:
[renyl@localhost lkp-tests]$ cat jobs/build-dpdk.yaml
suite: build-dpdk
testcase: build-dpdk
category: functional

testbox: vm-lkp-nex04-8G

branch: linus/master
commit: v4.5

dpdk_branch: dpdk/master
dpdk_commit: v2.2.0
dpdk_config:
- x86_64-native-linuxapp-gcc
dpdk_compiler:
- gcc-4.9            <======
- gcc-5              <======

build-dpdk:
[renyl@localhost lkp-tests]$

so use $dpdk_compiler to build kernel, and as a workaround to avoid "make prepare" run failed.

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>