distro/depends: add missing dependency package for piglit
To fix the following error info:
==> /tmp/stderr <==
/usr/bin/env: 'python3': No such file or directory

==> /tmp/stdout <==
igt/pm_rps/basic-api.seconds: .004277607
2016-08-30 05:40:47 piglit summary console /tmp/lkp/piglit-results/results.json.bz2

==> /tmp/stderr <==
/usr/bin/env: 'python3': No such file or directory
mv: cannot stat '/tmp/lkp/piglit-results/results.json.bz2': No such file or directory

==> /tmp/stderr <==
Traceback (most recent call last):
  File "/lkp/benchmarks/piglit/bin/piglit", line 42, in <module>
    import six
ImportError: No module named 'six'

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Fengguang Wu <fengguang.wu@intel.com>