rpmbuild use custom make too
parse make's stderr, like this

  ## ______________1:stdout
  /bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -g -I../src -std=c99 -D_GNU_SOURCE -Werror  -I/usr/include/httpd -I/usr/include/apr-1  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/openEuler/openEuler-hardened-cc1 -fasynchronous-unwind-tables-fstack-clash-protection -c -o mod_md_la-mod_md_config.lo `test -f 'mod_md_config.c' || echo './'`mod_md_config.clibtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -I../src -std=c99 -D_GNU_SOURCE -Werror -I/usr/include/httpd-I/usr/include/apr-1 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS-fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/openEuler/openEuler-hardened-cc1 -fasynchronous-unwind-tables -fstack-clash-protection -c mod_md_config.c  -fPIC -DPIC -o .libs/mod_md_la-mod_md_config.o
  ## ______________1:stderr
  mod_md_config.c: In function 'md_config_post_config':
  mod_md_config.c:903:24: error: implicit declaration of function 'ap_state_dir_relative'; did you mean 'ap_runtime_dir_relative'? [-Werror=implicit-function-declaration]
           mc->base_dir = ap_state_dir_relative(p, MD_DEFAULT_BASE_DIR);
                          ^~~~~~~~~~~~~~~~~~~~~
                          ap_runtime_dir_relative
  mod_md_config.c:903:22: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
           mc->base_dir = ap_state_dir_relative(p, MD_DEFAULT_BASE_DIR);
                        ^
  cc1: all warnings being treated as errors
  make[1]: *** [Makefile:881: mod_md_la-mod_md_config.lo] Error 1
  ## ______________1:enderr

Signed-off-by: Lin Jiaxin <ljx.joe@qq.com>