stats/nvml: fix no nvml-unit-tests.json is generated
The output is as below:
...
2017-03-03 16:55:27 ./RUNTESTS vmmalloc_calloc
error: PMEM_FS_DIR=/fs/pmem0 does not point to a PMEM device
RUNTESTS: stopping: vmmalloc_calloc/TEST0 failed, TEST=check FS=any BUILD=debug
2017-03-03 16:55:27 ./RUNTESTS vmmalloc_check_allocations
error: PMEM_FS_DIR=/fs/pmem0 does not point to a PMEM device
RUNTESTS: stopping: vmmalloc_check_allocations/TEST0 failed, TEST=check FS=any BUILD=debug
...

Because it fail without steup step, so stats will skip the fail info and make it no output.

Signed-off-by: Xiang Dai <xiangx.dai@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>