distro/aliyun: Improve download_ocfs2_tools()
If we want to download ocfs2-tools-devel's dependences,
we have to specify ocfs2-tools package as well because
yum cannot locate it.

Fix the following issue:
---------------------------------------------
Error: Package: ocfs2-tools-devel-1.8.6-11.el7.x86_64 (/ocfs2-tools-devel-1.8.6-11.el7.x86_64)
           Requires: ocfs2-tools = 1.8.6
---------------------------------------------

Signed-off-by: Xiao Yang <xiaox.yang@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>