pkg/packetdrill: remove packetdrill.patch since source tree have applied it
Fix the error when makepkg:
---------------------------------------------
 ERROR: A failure occurred in patch_source().
    Aborting...
--------------------------------------------

Packetdrill git have merged the following patch, which have same change
as packetdrill.patch in lkp-tests. So remove it from lkp-tests.
-----------------------------------------------------------
  commit: 977dbfe110ea080f9215557fff5c13465a12bbe7
  packetdrill: update tcp PSH expectation to latest upstream
------------------------------------------------------------

Signed-off-by: Haiyan Song <haiyanx.song@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>