pack/kernel_selftests: fix openssl/opensslv.h not found
fix the following error:
```
xsang@inn://result/pack/kernel_selftests/vm-snb-32G/debian-x86_64-2018-04-03.cgz/x86_64-rhel-7.6/gcc-7/bebc6082da0a9f5d47a1ea2edc099bf671058bd4/3$
cat stderr
Extracting templates from packages: 100%
libnetlink.c:150:2: warning: #warning "libmnl required for error
support" [-Wcpp]
 #warning "libmnl required for error support"
  ^~~~~~~
scripts/sign-file.c:25:30: fatal error: openssl/opensslv.h: No such file
or directory
 #include <openssl/opensslv.h>
```

The cause of the error is the lack of libssl-dev.
After change:
```
6@inn$ pwd
/result/pack/kernel_selftests/vm-snb-32G/debian-x86_64-2018-04-03.cgz/x86_64-rhel-7.6/gcc-7/bebc6082da0a9f5d47a1ea2edc099bf671058bd4/6
6@inn$ cat stderr | grep "openssl/opensslv.h"
6@inn$
```

Signed-off-by: Zhou Hao <zhouhao@cn.fujitsu.com>
Signed-off-by: Philip Li <philip.li@intel.com>