lib: redirect yum localinstall message to /dev/null
[why]
fixup_packages will use 'yum localinstall',
but call fixup_packages before setup_network, the network is unavailable,
so 'yum localinstall' will cause the following error,
  Error: Failed to download metadata for repo 'OS': Cannot download
  repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

Signed-off-by: Cao Xueliang <caoxl78320@163.com>