tests/build-dpdk: add -fno-PIE option
Debian started to build the gcc with -fPIE by default so the kernel build ends before it starts properly with:
kernel/bounds.c:1:0: error: code model kernel does not support PIC mode

workaround this issue by adding "-fno-PIE" option.

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>