pkg/packetdrill: Revert e054d9b2b3afb for gettid compilation issue
Now packetdrill upstream has fix that compilation issue officially via
commit 5da3aa6e5752 ("packetdrill: skip defining gettid() on Linux with
glibc 2.30+"). e054d9b2b3afb will fail the compilation as following on
Clear Linux:
--------
run_system_call.c: In function ‘system_call_thread’:
run_system_call.c:3472:31: error: implicit declaration of function ‘packetdrill_gettid’ [-Werror=implicit-function-declaration]
 3472 |  state->syscalls->thread_id = packetdrill_gettid();
      |                               ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [<builtin>: run_system_call.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
Install packetdrill failed
--------

So, revert it.

Signed-off-by: Cao jin <jinx.cao@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>