stats/perf-stat: fix "in `block in parse': undefined method `[]' for nil:NilClass"
the error is due to unexpected end of perf-stat, *fields points to null.

each result line has 7 elements, and we expected the result output full elements

/result/aim7/performance-1BRD_48G-ext4-600-sync_disk_rw-ucode=0x700001c-monitor=3471/debian-10.4-x86_64-20200603.cgz/x86_64-rhel-8.3/gcc-9/18b04b6d608b394f2db33fca00ac7838a0c8779d/0$ cat perf-stat
    ... ...
       139.478674756,146633.37,msec,task-clock,146633365406,100.00,146.633,CPUs utilized
       139.478674756,

$ cat -n /lkp/lkp/src/stats/perf-stat
       149      if line.include? ','
       150        stime, *fields = line.split(',')

before:
/result/aim7/performance-1BRD_48G-ext4-600-sync_disk_rw-ucode=0x700001c-monitor=3472ca3d/lkp-cpl-4sp1/debian-10.4-x86_64-20200603.cgz/x86_64-rhel-8.3/gcc-9/18b04b6d608b394f2db33fca00ac7838a0c8779d/0$ /lkp/lkp/src/stats/perf-stat < perf-stat
    ... ...
    /lkp/lkp/src/stats/perf-stat:169:in `block in parse': undefined method `[]' for nil:NilClass (NoMethodError)
            from /lkp/lkp/src/stats/perf-stat:146:in `each_line'
            from /lkp/lkp/src/stats/perf-stat:146:in `parse'
            from /lkp/lkp/src/stats/perf-stat:223:in `<main>'

after:
/result/aim7/performance-1BRD_48G-ext4-600-sync_disk_rw-ucode=0x700001c-monitor=3472ca3d/lkp-cpl-4sp1/debian-10.4-x86_64-20200603.cgz/x86_64-rhel-8.3/gcc-9/18b04b6d608b394f2db33fca00ac7838a0c8779d/0$ /lkp/carel/src/stats/perf-stat < perf-stat
    ... ...
    total.instructions: 1708327062056.0
    overall.ipc: 0.048793258102858575
    overall.cpi: 20.494634686864956
    overall.MPKI: 16.620350701363098
    overall.cache-miss-rate%: 38.61300335449319
    overall.cycles-between-cache-misses: 3193.4962849585136
    overall.branch-miss-rate%: 1.0390763899870439
    overall.dTLB-load-miss-rate%: 0.06763264383349954
    overall.dTLB-store-miss-rate%: 0.026064628845073247
    overall.iTLB-load-miss-rate%: 56.67184136227896
    overall.instructions-per-iTLB-miss: 1975.292889629907
    overall.node-load-miss-rate%: 88.59649032010365
    overall.node-store-miss-rate%: 88.60430914578716

Signed-off-by: Carel Si <beibei.si@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>