Revert "will-it-scale: update package and add affinity parameter"
This reverts commit cf79c4fe43e00a76947cd5094b01a1e90156eacd.

/result/will-it-scale/performance-thread-100%-tlb_flush3-ucode=0x16/lkp-hsw-4ex1/debian-10.4-x86_64-20200603.cgz/x86_64-rhel-8.3/gcc-9/6efb943b8616ec53a5e444193dccf1af9ad627b5/3$ cat stderr
Events disabled
Traceback (most recent call last):
  File "./runtest.py", line 58, in <module>
    affinity = sys.argv[5]
IndexError: list index out of range

Signed-off-by: Philip Li <philip.li@intel.com>