git: rewrite release_commit_shas()
It's more efficient to query the commits in one single git command.

The linux tag pattern is made more strict to exclude v2.6.11 due to
error:

	wfg@inn /c/repo/linux% git show '--no-patch' '--format=%H' 'v2.6.11^{commit}'
	error: v2.6.11^{commit}: expected commit type, but the object dereferences to tree type
	error: v2.6.11^{commit}: expected commit type, but the object dereferences to tree type

Signed-off-by: Fengguang Wu <fengguang.wu@intel.com>