tests/chromeswap: fix library path
To fix the following error info:

==> /tmp/stderr <==
Traceback (most recent call last):
  File "/lkp/benchmarks/chromeswap/platform_CompressedSwapPerf.py", line 7, in <module>
    import logging, numpy, os, shutil, socket
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: libblas.so.3: cannot open shared object file: No such file or directory  <======

however this library "libblas.so.3" is existent.

root@lkp-hsw-d01 /tmp/lkp# ll /usr/lib/libblas/libblas.so.3
lrwxrwxrwx 1 root root 16 2016-07-15 09:31 /usr/lib/libblas/libblas.so.3 -> libblas.so.3.6.1
root@lkp-hsw-d01 /tmp/lkp# ll /usr/lib/lapack/liblapack.so.3
lrwxrwxrwx 1 root root 18 2016-07-15 09:31 /usr/lib/lapack/liblapack.so.3 -> liblapack.so.3.6.1

the root cause is due to these librarys not be included in default search path,
so set LD_LIBRARY_PATH to solve this issue.

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>