lib/bootstrap.sh: mount /var/lib/mysql/ for mysql
fix the issue
---------------
ERROR: There's not enough space in /var/lib/mysql/
---------------
need to mount /var/lib/mysql/ before installing mysql-server at runtime

Signed-off-by: leishaoting <leist.fnst@cn.fujitsu.com>

Signed-off-by: Philip Li <philip.li@intel.com>