pkg/libhugetlbfs-test: Update libhugetlbfs-test.patch
run_tests.py has switched python2 to python3 by commit 9380eba
of libhugetlbfs and module types has no attribute StringType
in python3, so replace "type(cmd) != types.StringType" with
"not isinstance(cmd, str)"

Fix the follwing issue:
--------------------------------
    if type(cmd) != types.StringType:
AttributeError: module 'types' has no attribute 'StringType'
--------------------------------

Signed-off-by: Xiao Yang <xiaox.yang@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>