kernel_selftests: add missing dependency packages
To fix the following error:

==> /tmp/stderr <==
mlock-random-test.c:7:28: fatal error: sys/capability.h: No such file or directory
 #include <sys/capability.h>
                            ^
compilation terminated.
make[1]: *** [mlock-random-test] Error 1

==> /tmp/stderr <==
./run_vmtests: line 125: sudo: command not found

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>