fix(install-dependencies.sh): fix some problems when configure lkp env
[Why]
1. param: '-y'
   + ./sbin/install-dependencies.sh
   ...Omit...
   Total download size: 3.7 M
   Installed size: 18 M
   Is this ok [y/N]:

2. pkgs: gcc, gcc-c++, make
   ERROR:  Error installing rest-client:
           ERROR: Failed to build gem native extension.

       current directory: /usr/local/share/gems/gems/unf_ext-0.0.7.7/ext/unf_ext
   /usr/bin/ruby -r ./siteconf20201020-5195-h45kpd.rb extconf.rb
   checking for -lstdc++... *** extconf.rb failed ***
   Could not create Makefile due to some reason, probably lack of necessary
   libraries and/or headers.  Check the mkmf.log file for more details. You may
   need configuration options.
   ...Omit...
   /usr/share/ruby/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
   You have to install development tools first.
   ...Omit...

3. pkg: ruby-devel
   ERROR:  Error installing rest-client:
           ERROR: Failed to build gem native extension.

       current directory: /usr/local/share/gems/gems/unf_ext-0.0.7.7/ext/unf_ext
   /usr/bin/ruby -r ./siteconf20201020-5371-1gqrhar.rb extconf.rb
   mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

   extconf failed, exit code 1

   Gem files will remain installed in /usr/local/share/gems/gems/unf_ext-0.0.7.7 for inspection.
   Results logged to /usr/local/lib64/gems/ruby/unf_ext-0.0.7.7/gem_make.out

4. pkg: git
   + {LKP_SRC}/sbin/submit test-tools.yaml
   /usr/local/share/gems/gems/git-1.7.0/lib/git/lib.rb:989:in `command': git '-c' 'color.ui=false' version   2>&1:sh: git: command not found (Git::GitExecuteError)

Signed-off-by: Yu Chuan <13186087857@163.com>