tests/rpmbuild: mkdir /home/lkp if it does not exist
[Why]
lkp-test does not create /home/lkp if no useradd cmd.

ERROR: Home directory for user lkp not found in /etc/passwd.

Signed-off-by: Lin Jiaxin <ljx.joe@qq.com>