filters/need_kconfig.rb: fix "undefined method `split' for 200:Integer"
some configs need to set value, instead of y/m/n

- CMA_SIZE_MBYTES: 200

== before fix ==
Failures:

  1) filter/need_kconfig.rb when X needs to set value filters the job
     Failure/Error: expect { job.expand_params }.to raise_error Job::ParamError

       expected Job::ParamError, got #<NoMethodError: undefined method `split' for 200:Integer> with backtrace:
         # ./filters/need_kconfig.rb:70:in `block in check_all'
         # ./filters/need_kconfig.rb:66:in `each'
         # ./filters/need_kconfig.rb:66:in `check_all'
         # ./filters/need_kconfig.rb:138:in `block in expand_expression'
         # ./lib/erb.rb:51:in `eval'
         # ./lib/erb.rb:51:in `expand_expression'
         # ./lib/job.rb:640:in `evaluate_param'
         # ./lib/job.rb:687:in `block in expand_params'
         # ./lib/job.rb:79:in `block in for_each_in'
         # ./lib/job.rb:78:in `each'
         # ./lib/job.rb:78:in `for_each_in'
         # ./lib/job.rb:684:in `expand_params'
         # ./spec/filter_need_kconfig_spec.rb:52:in `block (4 levels) in <top (required)>'
         # ./spec/filter_need_kconfig_spec.rb:52:in `block (3 levels) in <top (required)>'
     # ./spec/filter_need_kconfig_spec.rb:52:in `block (3 levels) in <top (required)>'

  2) filter/need_kconfig.rb when the value of Y is the same as kconfig does not filters the job
     Failure/Error: context.eval(expr, file)

     NoMethodError:
       undefined method `split' for 200:Integer
     # ./filters/need_kconfig.rb:70:in `block in check_all'
     # ./filters/need_kconfig.rb:66:in `each'
     # ./filters/need_kconfig.rb:66:in `check_all'
     # ./filters/need_kconfig.rb:138:in `block in expand_expression'
     # ./lib/erb.rb:51:in `eval'
     # ./lib/erb.rb:51:in `expand_expression'
     # ./lib/job.rb:640:in `evaluate_param'
     # ./lib/job.rb:687:in `block in expand_params'
     # ./lib/job.rb:79:in `block in for_each_in'
     # ./lib/job.rb:78:in `each'
     # ./lib/job.rb:78:in `for_each_in'
     # ./lib/job.rb:684:in `expand_params'
     # ./spec/filter_need_kconfig_spec.rb:66:in `block (3 levels) in <top (required)>'

Finished in 0.03546 seconds (files took 0.13062 seconds to load)
11 examples, 2 failures

Failed examples:

rspec ./spec/filter_need_kconfig_spec.rb:47 # filter/need_kconfig.rb when X needs to set value filters the job rspec ./spec/filter_need_kconfig_spec.rb:57 # filter/need_kconfig.rb when the value of Y is the same as kconfig does not filters the job

== after fix ==
Finished in 0.02996 seconds (files took 0.13026 seconds to load)
11 examples, 0 failures

Signed-off-by: Carel Si <beibei.si@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>