stats/unixbench: exit when multiplier is nil
If unixbench goes wrong, the result is not normal and causes an Error:
-----
/lkp/lkp/src/stats/unixbench:31:in `<main>': undefined method `*' for
nil:NilClass (NoMethodError)
-----

To avoid that, add the check for the multiplier, if it's nil, use
log_error to put and exit directly.

Signed-off-by: Jiang Wenjia <wenjiax.jiang@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>