lkp-dev: add dependency on libtool-bin
To fix the following error:
-----------------------------------------------------------------------------------------------------------------------------
root@vm-lkp-wsx01-4G /renyl# make
autoheader
autoconf
./configure  --libexecdir=/usr/lib
checking for gcc... gcc
...
checking for make... /usr/bin/make
checking for glibtool... no
checking for libtool... no

FATAL ERROR: libtool does not seem to be installed.
xfstests cannot be built without a working GNU libtool installation.
Makefile:83: recipe for target 'include/builddefs' failed
...
root@vm-lkp-wsx01-4G-3 /renyl~# dpkg -l | grpe libtool
ii  libltdl-dev:amd64              2.4.2-1.11                   amd64        System independent dlopen wrapper for GNU libtool
ii  libtool                        2.4.2-1.11                   all          Generic library support script
------------------------------------------------------------------------------------------------------------------------------

According the error info, check the "libtool" packages and found it have been installed.
The root cause is to "./configure" don't found /usr/bin/libtool file in debian-system.

Currently, debian-system divide "/usr/bin/libool" and "/usr/bin/libtoolize" into the two different packages(libtool-bin and libtool),
so we need to both add them.

Signed-off-by: Yilong Ren <yilongx.ren@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>